#!/usr/bin/env python3
import Roms.DB.DataBase as DataBase
import Converter.PyTree as C
import sys

def usage():
    print("kdb: list: kdb -l <name.db>")
    print("kdb: query: kdb -q <name.db> <query>")
    print("kdb: fetch: kdb -f <name.db> <query>")
    sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 2 or len(sys.argv) > 4:
        print("kdb: wrong arguments.")
        usage()

    # argument 1 must be the command (-q or -f or -l)
    com = sys.argv[1]
    if com not in ['-q', '-f', '-l', '-h']:
        print("kdb: invalid command.")
        exit(1)
    
    # argument 2 must be the data base name    
    if len(sys.argv) >= 3: baseName = sys.argv[2]
    else: baseName = None

    # argument 3 must be the sql query
    if len(sys.argv) >= 4: query = sys.argv[3]
    else: query = None

    if com == '-f' or com == '-q':
        if baseName is None:
            print("kdb: baseName is missing.")
            exit(1)
        if query is None:
            print("kdb: query is missing.")
            exit(1)

    if com == '-h':
        usage()            

    # open db
    db = DataBase.DataBase(baseName)

    # list catalog
    if com == '-l':
        q = db.query()
        db.print(q, mode=0)
    elif com == '-q':
        q = db.query(query)
        db.print(q, mode=1)
    elif com == '-f':
        q = db.query(query)
        t = db.fetchTree(q)
        for c, ti in enumerate(t):
            C.convertPyTree2File(ti, 'out%d.cgns'%c)

    db.close()