LIBNAME = CompGeom
SOURCEF90 = 
SOURCEF77 = \
RotateMeshF.for\
CompBBoxOfCellF.for\
CompBoundingBox2F.for\
CompBoundingBoxUnstr2F.for\
CompBoundingBoxUnstrF.for\
CompBoundingBoxF.for\
CompCEBoxF.for\
CompMinDistF.for\
RectifyNormalsF.for\
SlopeF.for\
ParamF.for\
OnedmapF.for\
InterpF.for

include ../Make.inc
