#! /bin/bash

if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

PRODUCTION=1
# Destination docs
DEST="$CASSIOPEE/docs/doc"
# Destination tests unitaires
DEST2="$DEST/Examples/XCore"
# Destination des release notes
DEST3="$CASSIOPEE/docs/Download"

# do nothing for now
