#! /bin/sh
# cleanAll: enleve tous les .o, ...
. ./MODULES

for mod in $FULLMODULES
do
  if test -e $mod
  then
      cd $mod
      if [ "$ELSAPROD" = "" ]; then
          rm -fr build
      else
          rm -fr build/$ELSAPROD
      fi
      rm -fr .sconsign.dblite
      cd ..
  fi
done
