#! /bin/sh
# Print help message
usage() {
  echo -e "Usage: $0                                             : Install all modules"
  echo -e "       $0 --all, -a                                   : Install modules and docs"
  echo -e "       $0 --doc, -d                                   : Install docs only"
  echo -e "       $0 --cassiopee=<path_to_cassiopee_root_dir>    : Set env. var. CASSIOPEE"
  echo -e "       $0 --elsaprod=<production_name>                : Set env. var. ELSAPROD"
  echo -e "       $0 --prefix=<installation_path>                : Change default installation path"
  echo -e "       $0 --help, -h                                  : Print help message"
  exit 1
}

# Parse command-line arguments
PREFIX=""
INSTALL_DOCS=0
INSTALL_MODS=1
while [ "$1" != "" ]; do
  case "$1" in
    --all | -a)
      INSTALL_DOCS=1
      INSTALL_MODS=1
      ;;
    --cassiopee=*)
      export CASSIOPEE="${1#*=}"
      ;;
    --doc | -d)
      INSTALL_DOCS=1
      INSTALL_MODS=0
      ;;
    --elsaprod=*)
      export ELSAPROD="${1#*=}"
      ;;
    --prefix=*)
      export PREFIX="${1#*=}"
      ;;
    --help | -h)
      usage
      ;;
    *)
      echo "Invalid argument: $1"
      usage
      ;;
  esac
  shift
done

# Sanitise input arguments
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    usage
fi

if [ "$INSTALL_MODS" -eq 1 ]; then
    # Set install path
    if [ "$ELSAPROD" = "" ]; then
        echo "You must specify a ELSAPROD in your environment."
        echo "This variable identifies the processor type."
        usage
    fi
    if [ -z $PREFIX ]; then
        INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"
    else
        INSTALLPATH="$PREFIX/Dist/bin/$ELSAPROD"
    fi
fi

# Load module names
. ./MODULES

if [ "$PYTHONEXE" = "" ]; then
    export PYTHONEXE=python
fi

# Install modules and/or docs
for mod in $FULLMODULES
do
  if test -e $mod
  then
      cd $mod
      if [ "$INSTALL_MODS" -eq 1 ]; then
          ./install $INSTALLPATH
          [ $? != 0 ] && exit 1;
      fi
      if [ "$INSTALL_DOCS" -eq 1 ]; then
          cd doc
          ./install
          [ $? != 0 ] && exit 1;
          cd ..
      fi
      cd ..
  else
      echo 'Directory ', $mod, 'not found.'
  fi
done

# Fini avec la doc KCore pour genindex...
if [ "$INSTALL_DOCS" -eq 1 ]; then
    cd KCore/doc
    ./install
    [ $? != 0 ] && exit 1;
    cd ../..
fi

# Copy environment scripts
if [ "$INSTALL_MODS" -eq 1 ]; then
    if [ -z $PREFIX ]; then
        cp Envs/env_Cassiopee* "$CASSIOPEE"/Dist
        cp Envs/sh_Cassiopee*  "$CASSIOPEE"/Dist
    else
        cp Envs/env_Cassiopee* "$PREFIX"/Dist
        cp Envs/sh_Cassiopee*  "$PREFIX"/Dist
    fi
fi
