#! /bin/sh
# Print help message
usage() {
  echo -e "Usage: $0                                             : Install all modules"
  echo -e "       $0 --all                                       : Install modules and docs"
  echo -e "       $0 --doc                                       : Install docs only"
  echo -e "       $0 --cassiopee=</path/to/cassiopee/root/dir>   : Set env. var. CASSIOPEE and install all modules"
  echo -e "       $0 --elsaprod=<production_name>                : Set env. var. ELSAPROD and install all modules"
  echo -e "       $0 --help                                      : Print help message"
  exit 1
}

# Parse command-line arguments
INSTALL_DOCS=0
INSTALL_MODS=1
while [ "$1" != "" ]; do
  case "$1" in
    --all | -a)
      INSTALL_DOCS=1
      INSTALL_MODS=1
      ;;
    --cassiopee=*)
      export CASSIOPEE="${1#*=}"
      ;;
    --doc | -d)
      INSTALL_DOCS=1
      INSTALL_MODS=0
      ;;
    --elsaprod=*)
      export ELSAPROD="${1#*=}"
      ;;
    --help | -h)
      usage
      ;;
    *)
      echo "Invalid argument: $1"
      usage
      ;;
  esac
  shift
done

# Sanitise input arguments
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    usage
fi
if [ "$ELSAPROD" = "" ]; then
    echo "You must specify a ELSAPROD in your environment."
    echo "This variable identifies the processor type."
    usage
fi

# Set install path and load module names
INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"
. ./MODULES

if [ "$PYTHONEXE" = "" ]; then
    export PYTHONEXE=python
fi

# Install modules and/or docs
for mod in $FULLMODULES
do
  if test -e $mod
  then
      cd $mod
      if [ "$INSTALL_MODS" -eq 1 ]; then
          ./install
          [ $? != 0 ] && exit 1;
      fi
      if [ "$INSTALL_DOCS" -eq 1 ]; then
          cd doc
          ./install
          [ $? != 0 ] && exit 1;
          cd ..
      fi
      cd ..
  else
      echo 'Directory ', $mod, 'not found.'
  fi
done

# Fini avec la doc KCore pour genindex...
if [ "$INSTALL_DOCS" -eq 1 ]; then
    cd KCore/doc
    ./install
    [ $? != 0 ] && exit 1;
    cd ../..
fi

# Copy environment scripts
cp Envs/env_Cassiopee* "$CASSIOPEE"/Dist
cp Envs/sh_Cassiopee*  "$CASSIOPEE"/Dist
