#! /bin/sh
echo 'Installing Converter tests and doc'
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    PRODUCTION=0
    # Destination docs
    DEST="$CASSIOPEE/Dist/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Converter"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 1 ])
then
    PRODUCTION=0
    # Destination docs
    DEST="$1/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Converter"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 2 ])
then
    PRODUCTION=1
    # Destination docs
    DEST="$CASSIOPEE/WWW/cassiopee-web"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Converter"
    # Destination des release notes
    DEST3="$CASSIOPEE/WWW/Main/Download"
else
    echo 'install: install in $CASSIOPEE/Dist/doc'
    echo 'install <dir>: install in directory <dir/doc>.'
    exit
fi

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi
    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Apps/Modules/Converter/test Examples/Converter
fi
cd ..

# Build html
sphinx-build -b html ./source ./build

if ([ $PRODUCTION -eq 1 ])
then
    # Build pdf
    sphinx-build -b latex ./source ./build
    cd build
    sed -i 's/longtable}{LL}/longtable}{ll}/g' Internal.tex
    pdflatex Internal
    pdflatex Filter
    pdflatex ConverterMpi
    pdflatex elsAProfile
    pdflatex Converter
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    taghtml build/Internal.html
    sed -i 's/Converter\.Internal\.Converter\.Internal/Converter\.Internal/g' build/Internal.html
    sed -i 's/Converter\.pdf/Internal\.pdf/g' build/Internal.html
    cp build/Internal.html $DEST
    taghtml build/Filter.html
    sed -i 's/Converter\.Filter\.Converter\.Filter/Converter\.Filter/g' build/Filter.html
    sed -i 's/Converter\.pdf/Filter\.pdf/g' build/Filter.html
    cp build/Filter.html $DEST
    taghtml build/ConverterMpi.html
    sed -i 's/Converter\.Mpi\.Converter\.Mpi/Converter\.Mpi/g' build/ConverterMpi.html
    sed -i 's/Converter\.pdf/ConverterMpi\.pdf/g' build/ConverterMpi.html
    cp build/ConverterMpi.html $DEST
    taghtml build/elsAProfile.html
    sed -i 's/Converter\.elsAProfile\.Converter\.elsAProfile/Converter\.elsAProfile/g' build/elsAProfile.html
    sed -i 's/Converter\.pdf/elsAProfile\.pdf/g' build/elsAProfile.html
    cp build/elsAProfile.html $DEST
    taghtml build/Converter.html
    sed -i 's/Converter\.Converter/Converter/g' build/Converter.html
    cp build/Converter.html $DEST

    cp build/Internal.pdf $DEST
    cp build/Filter.pdf $DEST
    cp build/ConverterMpi.pdf $DEST
    cp build/elsAProfile.pdf $DEST
    cp build/Converter.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../Converter/Converter.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='Converter-'$version1'.txt'
    cp Converter.txt $DEST3/$v
fi
