#! /bin/sh
# cleanAll: enleve tous les .o, ...
. ./MODULES

for mod in $FULLMODULES
do
  if test -e $mod
  then
      cd $mod
      rm -fr build/spiro_r8
      rm -fr .sconsign.dblite
      cd ..
  fi
done
