#! /bin/sh
# install     : compile et installe tous les modules
# install doc : installe uniquement les docs
# install opensource : compile et installe la version open-source
# install all : installe les modules + docs
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit 1
    fi
    if [ "$ELSAPROD" = "" ]; then
        echo "You must specify a ELSAPROD in your environment."
        echo "This variable identifies the processor type."
        exit 1
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    if [ "$ELSAPROD" = "" ]; then
        echo "You must specify a ELSAPROD in your environment."
        echo "This variable identifies the processor type."
        exit 1
    fi
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo 'install <dir>: install in directory <dir>.'
    exit 1
fi

. ./MODULES

if [ "$1" = "opensource" ]; then
    $PYTHONEXE $CASSIOPEE/Apps/util/STUBS/stubs.py stubit
fi

for mod in $FULLMODULES
do
  if test -e $mod
  then
      cd $mod
      if [ "$1" = "" -o "$1" = "all" ]; then
          ./install
          [ $? != 0 ] && exit 1;
      fi
      if [ "$1" = "doc" -o "$1" = "all" ]; then
          cd doc
          ./install 1 2
          [ $? != 0 ] && exit 1;
          cd ..
      fi
      cd ..
  else
      echo 'Directory ',$mod, 'not found.'
  fi
done

if [ "$1" = "opensource" ]; then
    $PYTHONEXE $CASSIOPEE/Apps/util/STUBS/stubs.py unstubit
fi

# Fini avec la doc KCore pour genindex...
if [ "$1" = "doc" -o "$1" = "all" ]; then
    cd KCore/doc
    ./install 1 2
    [ $? != 0 ] && exit 1;
    cd ../..
fi

# Installation des fichiers d'environnement
cp Envs/env_Cassiopee* "$CASSIOPEE"/Dist
cp Envs/sh_Cassiopee*  "$CASSIOPEE"/Dist
