#! /bin/sh
echo 'Installing Initiator tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

if ([ $# -eq 0 ])
then
    PRODUCTION=0
    # Destination docs
    DEST="./doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Initiator"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 2 ])
then
    PRODUCTION=1
    # Destination docs
    DEST="$CASSIOPEE/docs/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Initiator"
    # Destination des release notes
    DEST3="$CASSIOPEE/docs/Download"
else
    echo 'install: install locally'
    echo 'install <dir>: install in docs/doc.'
    exit
fi

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi

    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Cassiopee/Initiator/test Examples/Initiator
fi
cd ..

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build
if ([ $PRODUCTION -eq 1 ])
then
# Build pdf
    sphinx-build -b latex ./source ./build
    cd build
    pdflatex Initiator >& /dev/null
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    sed -i 's/Initiator.Initiator/Initiator/g' build/Initiator.html
    cp build/Initiator.html $DEST
    cp build/Initiator.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../Initiator/Initiator.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='Initiator-'$version1'.txt'
    cp Initiator.txt $DEST3/$v
fi
