PROG = usurp	

SRCS =	BuildGraphM.f90 CalculateForcesAndMomentsM.f90 \
	CalculatePolygonAreaM.f90 CalculateProjectedAreasM.f90 \
	CalculateVolumesM.f90 CheckInputM.f90 CheckPanelPairM.f90 \
	CheckRatiosM.f90 CheckTrianglesM.f90 ConvertPanelToPolygonM.f90 \
	CreateNewNodeListM.f90 CreateTrianglesM.f90 CutOutStringsM.f90 \
	DeallocatePanelsM.f90 DefinePanelsM.f90 DetermineSurfaceOverlapM.f90 \
	EdgeDataM.f90 ExaminePrioritiesM.f90 FoMoArraysM.f90 \
	GarbageCollectorM.f90 GetUserInputM.f90 GraphProceduresM.f90 \
	GroupInfoM.f90 InsertNodeM.f90 IntrTypeM.f90 LoadPanelsM.f90 \
	LoadPanelsNPHASEM.f90 MapTriQM.f90 NetAllocM.f90 \
	OutputForcesAndMomentsM.f90 OutputOVERFLOWM.f90 OverlappedM.f90 \
	PatchInfoM.f90 PreReadBCinM.f90 PreReadBCSM.f90 PreReadGenericM.f90 \
	PreReadNPHASEM.f90 PreReadOVERFLOWM.f90 PreReadUNCLEMM.f90 \
	PrintPolyM.f90 PriPairsM.f90 ProcessPairProceduresM.f90 \
	ReadPanelWeightsM.f90 ResolveEdgeIntersectionsM.f90 RotateBackM.f90 \
	RTreeProceduresM.f90 RTreeTypesM.f90 ShrinkVertexListM.f90 sort2M.f90 \
	StorePatchesCFDSHIPM.f90 StorePatchesGenericM.f90 \
	StorePatchesUNCLEM.f90 StructuredPatchProceduresM.f90 \
	TecplotNPHASEM.f90 TimeKeeperM.f90 TranslationArraysM.f90 \
	TriQuadM.f90 TypesM.f90 UnusedVerticesM.f90 UserInputM.f90 usurp.f90 \
	VertexDataM.f90 VolumeArraysM.f90 WriteMixsurFMPM.f90 \
	WritePanelWeightsM.f90 CommandLineM.F90 DPLRM.F90 my_cpu_timeM.F90 \
	StorePatchesOVERFLOWM.F90 TecplotTrianglesM.F90 WriteGridIBIM.F90 \
	WritePatchesM.F90 WriteTriQM.F90 ctype.c gpc.c \
	gpc_c_translator_clip.c gpc_c_translator_strip.c share_eps.c \
	triangle.c triangle_translator_c.c

OBJS =	BuildGraphM.o CalculateForcesAndMomentsM.o CalculatePolygonAreaM.o \
	CalculateProjectedAreasM.o CalculateVolumesM.o CheckInputM.o \
	CheckPanelPairM.o CheckRatiosM.o CheckTrianglesM.o \
	ConvertPanelToPolygonM.o CreateNewNodeListM.o CreateTrianglesM.o \
	CutOutStringsM.o DeallocatePanelsM.o DefinePanelsM.o \
	DetermineSurfaceOverlapM.o EdgeDataM.o ExaminePrioritiesM.o \
	FoMoArraysM.o GarbageCollectorM.o GetUserInputM.o GraphProceduresM.o \
	GroupInfoM.o InsertNodeM.o IntrTypeM.o LoadPanelsM.o \
	LoadPanelsNPHASEM.o MapTriQM.o NetAllocM.o OutputForcesAndMomentsM.o \
	OutputOVERFLOWM.o OverlappedM.o PatchInfoM.o PreReadBCinM.o \
	PreReadBCSM.o PreReadGenericM.o PreReadNPHASEM.o PreReadOVERFLOWM.o \
	PreReadUNCLEMM.o PrintPolyM.o PriPairsM.o ProcessPairProceduresM.o \
	ReadPanelWeightsM.o ResolveEdgeIntersectionsM.o RotateBackM.o \
	RTreeProceduresM.o RTreeTypesM.o ShrinkVertexListM.o sort2M.o \
	StorePatchesCFDSHIPM.o StorePatchesGenericM.o StorePatchesUNCLEM.o \
	StructuredPatchProceduresM.o TecplotNPHASEM.o TimeKeeperM.o \
	TranslationArraysM.o TriQuadM.o TypesM.o UnusedVerticesM.o \
	UserInputM.o usurp.o VertexDataM.o VolumeArraysM.o WriteMixsurFMPM.o \
	WritePanelWeightsM.o CommandLineM.o DPLRM.o my_cpu_timeM.o \
	StorePatchesOVERFLOWM.o TecplotTrianglesM.o WriteGridIBIM.o \
	WritePatchesM.o WriteTriQM.o ctype.o gpc.o gpc_c_translator_clip.o \
	gpc_c_translator_strip.o share_eps.o triangle.o \
	triangle_translator_c.o

MODS =	buildgraphm.mod calculateforcesandmomentsm.mod \
	calculatepolygonaream.mod calculateprojectedareasm.mod \
	calculatevolumesm.mod checkinputm.mod checkpanelpairm.mod \
	checkratiosm.mod checktrianglesm.mod convertpaneltopolygonm.mod \
	createnewnodelistm.mod createtrianglesm.mod cutoutstringsm.mod \
	deallocatepanelsm.mod definepanelsm.mod determinesurfaceoverlapm.mod \
	edgedata.mod examineprioritiesm.mod fomoarrays.mod \
	garbagecollectorm.mod getuserinputm.mod graphprocedures.mod \
	groupinfo.mod insertnodem.mod intrtype.mod loadpanelsm.mod \
	loadpanelsnphasem.mod maptriqm.mod netalloc.mod \
	outputforcesandmomentsm.mod outputoverflowm.mod overlappedm.mod \
	patchinfo.mod prereadbcinm.mod prereadbcsm.mod prereadgenericm.mod \
	prereadnphasem.mod prereadoverflowm.mod prereadunclemm.mod \
	printpolym.mod pripairs.mod processpairprocedures.mod \
	readpanelweightsm.mod resolveedgeintersectionsm.mod rotatebackm.mod \
	rtreeprocedures.mod rtreetypes.mod shrinkvertexlistm.mod sort2m.mod \
	storepatchescfdshipm.mod storepatchesgenericm.mod \
	storepatchesunclem.mod structuredpatchprocedures.mod \
	tecplotnphasem.mod timekeeper.mod translationarrays.mod triquadm.mod \
	types.mod unusedverticesm.mod userinput.mod vertexdata.mod \
	volumearrays.mod writemixsurfmpm.mod writepanelweightsm.mod \
	commandlinem.mod dplrm.mod my_cpu_timem.mod storepatchesoverflowm.mod \
	tecplottrianglesm.mod writegridibim.mod writepatchesm.mod \
	writetriqm.mod

CMD =	all

LIBS = $(TECIO_HOME) $(FXDR_HOME)	

CC = gcc
CFLAGS = -c -O2
FC = 
FFLAGS = 
F90 = pgf90
F90FLAGS = -c -O2 -Mstandard -Mbyteswapio -DUSE_TECPLOT -DMCLOCK
LDFLAGS = -O2

include Make.sys

all: ${PROG}

${PROG}: ${OBJS}
	${F90} ${LDFLAGS} -o $@ ${OBJS} ${LIBS}

clean:
	rm -f ${OBJS} ${MODS}

deinstall:
	rm -f ${OBJS} ${MODS} ${PROG}

.SUFFIXES: ${SUFFIXES} .f90 .F90 .c .obj

.f90.o:
	${F90} ${F90FLAGS} $<

.F90.o:
	${F90} ${F90FLAGS} $<

.c.o:
	${CC} ${CFLAGS} $<

BuildGraphM.o: GraphProceduresM.o IntrTypeM.o NetAllocM.o PatchInfoM.o \
	TypesM.o UserInputM.o my_cpu_timeM.o
CalculateForcesAndMomentsM.o: FoMoArraysM.o IntrTypeM.o NetAllocM.o \
	PatchInfoM.o TypesM.o UserInputM.o my_cpu_timeM.o
CalculatePolygonAreaM.o: IntrTypeM.o TypesM.o
CalculateProjectedAreasM.o: IntrTypeM.o TypesM.o UserInputM.o my_cpu_timeM.o
CalculateVolumesM.o: IntrTypeM.o VolumeArraysM.o
CheckInputM.o: UserInputM.o
CheckPanelPairM.o: IntrTypeM.o OverlappedM.o TypesM.o UserInputM.o
CheckRatiosM.o: IntrTypeM.o TypesM.o UserInputM.o my_cpu_timeM.o
CheckTrianglesM.o: IntrTypeM.o NetAllocM.o RotateBackM.o TypesM.o \
	UserInputM.o my_cpu_timeM.o
ConvertPanelToPolygonM.o: IntrTypeM.o NetAllocM.o TypesM.o
CreateNewNodeListM.o: IntrTypeM.o NetAllocM.o RotateBackM.o TypesM.o \
	UserInputM.o VertexDataM.o my_cpu_timeM.o
CreateTrianglesM.o: GarbageCollectorM.o IntrTypeM.o NetAllocM.o PrintPolyM.o \
	ProcessPairProceduresM.o TriQuadM.o TypesM.o UserInputM.o \
	my_cpu_timeM.o
CutOutStringsM.o: IntrTypeM.o NetAllocM.o OverlappedM.o PatchInfoM.o TypesM.o \
	UserInputM.o VertexDataM.o my_cpu_timeM.o
DeallocatePanelsM.o: EdgeDataM.o FoMoArraysM.o GroupInfoM.o IntrTypeM.o \
	NetAllocM.o PatchInfoM.o PriPairsM.o ProcessPairProceduresM.o \
	TypesM.o UserInputM.o VertexDataM.o my_cpu_timeM.o
DefinePanelsM.o: ConvertPanelToPolygonM.o IntrTypeM.o TypesM.o UserInputM.o \
	VertexDataM.o my_cpu_timeM.o
DetermineSurfaceOverlapM.o: IntrTypeM.o OverlappedM.o PatchInfoM.o \
	ProcessPairProceduresM.o TimeKeeperM.o TypesM.o UserInputM.o \
	VertexDataM.o
ExaminePrioritiesM.o: IntrTypeM.o PatchInfoM.o PriPairsM.o UserInputM.o \
	my_cpu_timeM.o
FoMoArraysM.o: IntrTypeM.o
GarbageCollectorM.o: IntrTypeM.o NetAllocM.o TypesM.o UserInputM.o
GetUserInputM.o: IntrTypeM.o UserInputM.o my_cpu_timeM.o
GraphProceduresM.o: IntrTypeM.o
InsertNodeM.o: IntrTypeM.o NetAllocM.o TypesM.o UserInputM.o
LoadPanelsM.o: EdgeDataM.o IntrTypeM.o NetAllocM.o PatchInfoM.o TypesM.o \
	UserInputM.o my_cpu_timeM.o
LoadPanelsNPHASEM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o TypesM.o \
	UserInputM.o VertexDataM.o my_cpu_timeM.o
MapTriQM.o: IntrTypeM.o NetAllocM.o TypesM.o UserInputM.o VertexDataM.o \
	my_cpu_timeM.o
OutputForcesAndMomentsM.o: CalculateVolumesM.o FoMoArraysM.o IntrTypeM.o \
	NetAllocM.o PatchInfoM.o UserInputM.o VolumeArraysM.o my_cpu_timeM.o
OutputOVERFLOWM.o: FoMoArraysM.o GroupInfoM.o IntrTypeM.o PatchInfoM.o \
	UserInputM.o my_cpu_timeM.o
OverlappedM.o: IntrTypeM.o
PreReadBCinM.o: NetAllocM.o PatchInfoM.o StructuredPatchProceduresM.o \
	TypesM.o UserInputM.o
PreReadBCSM.o: NetAllocM.o PatchInfoM.o StructuredPatchProceduresM.o TypesM.o \
	UserInputM.o
PreReadGenericM.o: PatchInfoM.o StructuredPatchProceduresM.o TypesM.o \
	UserInputM.o
PreReadNPHASEM.o: NetAllocM.o PatchInfoM.o StructuredPatchProceduresM.o \
	UserInputM.o VertexDataM.o
PreReadOVERFLOWM.o: EdgeDataM.o GroupInfoM.o IntrTypeM.o NetAllocM.o \
	PatchInfoM.o PriPairsM.o StructuredPatchProceduresM.o TypesM.o \
	UserInputM.o VertexDataM.o
PreReadUNCLEMM.o: NetAllocM.o PatchInfoM.o StructuredPatchProceduresM.o \
	TypesM.o UserInputM.o
PrintPolyM.o: TypesM.o UserInputM.o
ProcessPairProceduresM.o: ConvertPanelToPolygonM.o GarbageCollectorM.o \
	InsertNodeM.o IntrTypeM.o NetAllocM.o PatchInfoM.o PriPairsM.o \
	PrintPolyM.o TranslationArraysM.o TypesM.o UserInputM.o VertexDataM.o \
	my_cpu_timeM.o
ReadPanelWeightsM.o: IntrTypeM.o PatchInfoM.o TypesM.o UserInputM.o \
	my_cpu_timeM.o
ResolveEdgeIntersectionsM.o: EdgeDataM.o InsertNodeM.o IntrTypeM.o \
	NetAllocM.o RotateBackM.o TypesM.o UserInputM.o VertexDataM.o \
	my_cpu_timeM.o sort2M.o
RotateBackM.o: IntrTypeM.o
RTreeProceduresM.o: IntrTypeM.o NetAllocM.o OverlappedM.o PatchInfoM.o \
	ProcessPairProceduresM.o RTreeTypesM.o TimeKeeperM.o TypesM.o \
	UserInputM.o
RTreeTypesM.o: IntrTypeM.o TypesM.o
ShrinkVertexListM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o TypesM.o \
	UserInputM.o VertexDataM.o my_cpu_timeM.o
StorePatchesCFDSHIPM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o TypesM.o \
	UserInputM.o VertexDataM.o my_cpu_timeM.o
StorePatchesGenericM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o TypesM.o \
	UserInputM.o VertexDataM.o my_cpu_timeM.o
StorePatchesUNCLEM.o: CalculateVolumesM.o IntrTypeM.o NetAllocM.o \
	PatchInfoM.o TypesM.o UserInputM.o VertexDataM.o VolumeArraysM.o \
	my_cpu_timeM.o
StructuredPatchProceduresM.o: EdgeDataM.o NetAllocM.o PatchInfoM.o TypesM.o \
	VertexDataM.o
TecplotNPHASEM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o RotateBackM.o TypesM.o \
	UserInputM.o VertexDataM.o my_cpu_timeM.o
TimeKeeperM.o: IntrTypeM.o
TranslationArraysM.o: IntrTypeM.o
TriQuadM.o: IntrTypeM.o NetAllocM.o ProcessPairProceduresM.o TypesM.o \
	UserInputM.o
TypesM.o: IntrTypeM.o
UnusedVerticesM.o: IntrTypeM.o NetAllocM.o TypesM.o UserInputM.o \
	VertexDataM.o my_cpu_timeM.o
UserInputM.o: IntrTypeM.o
usurp.o: BuildGraphM.o CalculateForcesAndMomentsM.o CalculatePolygonAreaM.o \
	CalculateProjectedAreasM.o CheckInputM.o CheckPanelPairM.o \
	CheckRatiosM.o CheckTrianglesM.o CommandLineM.o CreateNewNodeListM.o \
	CreateTrianglesM.o CutOutStringsM.o DPLRM.o DeallocatePanelsM.o \
	DefinePanelsM.o DetermineSurfaceOverlapM.o ExaminePrioritiesM.o \
	GetUserInputM.o IntrTypeM.o LoadPanelsM.o LoadPanelsNPHASEM.o \
	MapTriQM.o NetAllocM.o OutputForcesAndMomentsM.o OutputOVERFLOWM.o \
	PatchInfoM.o PreReadBCSM.o PreReadBCinM.o PreReadGenericM.o \
	PreReadNPHASEM.o PreReadOVERFLOWM.o PreReadUNCLEMM.o \
	ProcessPairProceduresM.o RTreeProceduresM.o RTreeTypesM.o \
	ReadPanelWeightsM.o ResolveEdgeIntersectionsM.o ShrinkVertexListM.o \
	StorePatchesCFDSHIPM.o StorePatchesGenericM.o StorePatchesOVERFLOWM.o \
	StorePatchesUNCLEM.o TecplotNPHASEM.o TecplotTrianglesM.o \
	TimeKeeperM.o TypesM.o UnusedVerticesM.o UserInputM.o WriteGridIBIM.o \
	WriteMixsurFMPM.o WritePanelWeightsM.o WritePatchesM.o WriteTriQM.o \
	my_cpu_timeM.o
VertexDataM.o: IntrTypeM.o
VolumeArraysM.o: IntrTypeM.o
WriteMixsurFMPM.o: GroupInfoM.o IntrTypeM.o PatchInfoM.o UserInputM.o \
	VertexDataM.o my_cpu_timeM.o
WritePanelWeightsM.o: IntrTypeM.o PatchInfoM.o TypesM.o UserInputM.o \
	my_cpu_timeM.o
CommandLineM.o: IntrTypeM.o NetAllocM.o UserInputM.o
DPLRM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o StorePatchesUNCLEM.o \
	StructuredPatchProceduresM.o TypesM.o UserInputM.o VertexDataM.o \
	VolumeArraysM.o my_cpu_timeM.o
my_cpu_timeM.o: IntrTypeM.o
StorePatchesOVERFLOWM.o: CalculateVolumesM.o IntrTypeM.o NetAllocM.o \
	PatchInfoM.o TypesM.o UserInputM.o VertexDataM.o VolumeArraysM.o \
	my_cpu_timeM.o
TecplotTrianglesM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o TypesM.o \
	UserInputM.o VertexDataM.o my_cpu_timeM.o
WriteGridIBIM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o TypesM.o UserInputM.o \
	VertexDataM.o my_cpu_timeM.o
WritePatchesM.o: IntrTypeM.o NetAllocM.o PatchInfoM.o TypesM.o UserInputM.o \
	VertexDataM.o my_cpu_timeM.o
WriteTriQM.o: IntrTypeM.o NetAllocM.o TypesM.o UserInputM.o VertexDataM.o \
	my_cpu_timeM.o
gpc.o: gpc.h
gpc_c_translator_clip.o: gpc.h
gpc_c_translator_strip.o: gpc.h
share_eps.o: gpc.h
triangle.o: triangle.h
triangle_translator_c.o: triangle.h
