#! /bin/sh
if test -e "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.py"
then
    python "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.py" $1
else
    python "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.pyc" $1
fi
