#! /bin/sh
if [ "$PYTHONEXE" = "" ]; then
    export PYTHONEXE=python
fi

which vglrun &>/dev/null
if [ $? -eq 0 ]; then
	if test -e "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.py"
	then
    	vglrun $PYTHONEXE "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.py" "$@"
	else
    	vglrun $PYTHONEXE "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.pyc" "$@"
	fi	
else
	if test -e "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.py"
	then
    	$PYTHONEXE "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.py" "$@"
	else
    	$PYTHONEXE "$CASSIOPEE/Dist/bin/$ELSAPROD/tkCassiopee.pyc" "$@"
	fi
fi
