#!/bin/sh
echo 'Installing usurp'
if (test -e .Obj/$ELSAPROD/libeusurp.so)
then
    cp .Obj/$ELSAPROD/libeusurp.so $ELSADIST/Dist/bin/$ELSAPROD/Usurpl.so
fi
if (test -e .Obj/$ELSAPROD/libeusurp.dylib)
then
    cp .Obj/$ELSAPROD/libeusurp.dylib $ELSADIST/Dist/bin/$ELSAPROD/Usurpl.so
fi
cp Usurp.py $ELSADIST/Dist/lib/py/
