LIBNAME = GeneratorF
SOURCEF90 =
SOURCEF77 = MeshqualF.for HgF.for Hg2F.for Hg3F.for Hg4F.for DecbtF.for SolbtF.for PtridF.for DecF.for SolF.for GelgF.for StretchF.for MetsF.for CoeffttmF.for Sor9ptF.for
include ../Make.inc
