#! /bin/sh
echo 'Installing Converter tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

PRODUCTION=1
# Destination docs
DEST="$CASSIOPEE/docs/doc"
# Destination tests unitaires
DEST2="$DEST/Examples/Converter"
# Destination des release notes
DEST3="$CASSIOPEE/docs/Download"

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi
    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Cassiopee/Converter/test Examples/Converter
fi
cd ..

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build
[ $? != 0 ] && exit 1;

if ([ $PRODUCTION -eq 1 ])
then
    # Build pdf
    sphinx-build -b latex ./source ./build
    [ $? != 0 ] && exit 1;
    cd build
    sed -i 's/longtable}{LL}/longtable}{ll}/g' Internal.tex
    pdflatex Internal
    [ $? != 0 ] && exit 1;
    pdflatex Filter
    [ $? != 0 ] && exit 1;
    pdflatex ConverterMpi
    [ $? != 0 ] && exit 1;
    pdflatex elsAProfile
    [ $? != 0 ] && exit 1;
    pdflatex Converter
    [ $? != 0 ] && exit 1;
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    sed -i 's/Converter\.Internal\.Converter\.Internal/Converter\.Internal/g' build/Internal.html
    sed -i 's/Converter\.pdf/Internal\.pdf/g' build/Internal.html
    cp build/Internal.html $DEST
    sed -i 's/Converter\.Filter\.Converter\.Filter/Converter\.Filter/g' build/Filter.html
    sed -i 's/Converter\.pdf/Filter\.pdf/g' build/Filter.html
    cp build/Filter.html $DEST
    sed -i 's/Converter\.Mpi\.Converter\.Mpi/Converter\.Mpi/g' build/ConverterMpi.html
    sed -i 's/Converter\.pdf/ConverterMpi\.pdf/g' build/ConverterMpi.html
    cp build/ConverterMpi.html $DEST
    sed -i 's/Converter\.elsAProfile\.Converter\.elsAProfile/Converter\.elsAProfile/g' build/elsAProfile.html
    sed -i 's/Converter\.pdf/elsAProfile\.pdf/g' build/elsAProfile.html
    cp build/elsAProfile.html $DEST
    sed -i 's/Converter\.Converter/Converter/g' build/Converter.html
    cp build/Converter.html $DEST

    cp build/Internal.pdf $DEST
    cp build/Filter.pdf $DEST
    cp build/ConverterMpi.pdf $DEST
    cp build/elsAProfile.pdf $DEST
    cp build/Converter.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../Converter/Converter.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='Converter-'$version1'.txt'
    cp Converter.txt $DEST3/$v
fi
