#! /bin/sh
#
# Installation du module KCore
#
# 1. Modifier le fichier KCore/installBase.py
# 2. Pour l'installation standard (dans $CASSIOPEE/Dist/bin/$ELSAPROD/),
# taper  : ./install
#    Pour une installation dans un repertoire <rep>, taper : ./install <rep>
# Puis suivre les instructions.
#
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit 1
    fi
    if [ "$ELSAPROD" = "" ]; then
        export ELSAPROD=x86_r8
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or- '
    echo 'install <dir>: install in directory <dir>.'
    exit 1
fi

if [ "$PYTHONEXE" != "" ]; then
    alias python=$PYTHONEXE
fi

# Compilation et installation
sconsf=`which scons`
which scons &>/dev/null
if [ $? -eq 0 ]; then
    if [ "$OMP_NUM_THREADS" != "" ]; then
        export SCONSOPT="-j $OMP_NUM_THREADS"
        echo "Parallel compilation on "$OMP_NUM_THREADS" cores"
    else
        export SCONSOPT=""
    fi
    python $sconsf install prefix="$INSTALLPATH" "$SCONSOPT"
    [ $? != 0 ] && exit 1;
    #Touch KCore/kcore.cpp
    rm -f build/lib.*/KCore/kcore.*
    rm -f build/lib.*/KCore/kcore-*.*
    python -c "import Dist; Dist.symLinks()"
    python setup.py install --prefix="$INSTALLPATH"
    #python -m pip install --target="$INSTALLPATH/lib/python3.8/site-packages" .
    [ $? != 0 ] && exit 1;
else
    python setupLegacy.py install --prefix="$INSTALLPATH"
    [ $? != 0 ] && exit 1;
fi

# Install libkcore
python installLib.py

# Check installation
python test/t1.py
