#! /bin/sh
echo 'Installing Geom tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

PRODUCTION=1
# Destination docs
DEST="$CASSIOPEE/docs/doc"
# Destination tests unitaires
DEST2="$DEST/Examples/Geom"
# Destination des release notes
DEST3="$CASSIOPEE/docs/Download"

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi
    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Cassiopee/Geom/test Examples/Geom
fi
cd ..

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build
[ $? != 0 ] && exit 1;
if ([ $PRODUCTION -eq 1 ])
then
# Build pdf
    sphinx-build -b latex ./source ./build
    [ $? != 0 ] && exit 1;
    cd build
    pdflatex Geom
    [ $? != 0 ] && exit 1;
    pdflatex Geom_IBM
    [ $? != 0 ] && exit 1;
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    sed -i 's/Geom.Geom/Geom/g' build/Geom.html
    cp build/Geom.html $DEST
    cp build/Geom.pdf $DEST

    sed -i 's/Geom.Geom_IBM.Geom.Geom_IBM/Geom.Geom_IBM/g' build/Geom_IBM.html
    sed -i 's/Geom\.pdf/Geom_IBM\.pdf/g' build/Geom_IBM.html
    cp build/Geom_IBM.html $DEST
    cp build/Geom_IBM.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../Geom/Geom.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='Geom-'$version1'.txt'
    cp Geom.txt $DEST3/$v
fi
