#==============================================================================
# Fichiers c++
#==============================================================================

cpp_srcs = ['all/all_allo.c', 'all/all_allo_const.h',
            'ch/ch_dist_graph.c', 'ch/ch_init_dist.c',
            'ch/ch_input_assign.c',
            'ch/ch_input_geom.c', 'ch/ch_input_graph.c', 'ch/ch_input_read.c',
            'coloring/bucket.c', 'coloring/coloring.c',
            'coloring/color_test.c',
            'coloring/g2l_hash.c',
            'graph/graph.c',
            'ha/divide_machine.c', 'ha/get_processor_name.c',
            'ha/ha_ovis.c', 'hier/hier.c',
            'hier/hier_free_struct.c', 'hsfc/hsfc.c', 'hsfc/hsfc_box_assign.c',
            'hsfc/hsfc_hilbert.c',
            'hsfc/hsfc_point_assign.c',
            'lb/lb_balance.c', 'lb/lb_box_assign.c',
            'lb/lb_copy.c', 'lb/lb_eval.c', 'lb/lb_free.c', 'lb/lb_init.c',
            'lb/lb_invert.c', 'lb/lb_migrate.c', 'lb/lb_part2proc.c', 'lb/lb_point_assign.c',
            'lb/lb_remap.c', 'lb/lb_set_fn.c', 'lb/lb_set_method.c', 'lb/lb_set_part_sizes.c',
            'lb/low_mem_lb_migrate.c', 'matrix/matrix_build.c', 'matrix/matrix_distribute.c',
            'matrix/matrix_operations.c', 'matrix/matrix_sym.c', 'matrix/matrix_utils.c',
            'order/hsfcOrder.c',
            'order/order.c', 'order/order_struct.c',
            'order/order_tools.c', 'order/perm.c', 'par/par_average.c',
            'par/par_bisect.c', 'par/par_median.c',
            'par/par_median_randomized.c', 'par/par_stats.c',
            'par/par_sync.c', 'par/par_tflops_special.c',
            'params/assign_param_vals.c', 'params/bind_param.c', 'params/check_param.c',
            'params/free_params.c', 'params/key_params.c',
            'params/print_params.c', 'params/set_param.c',
            'phg/phg.c', 'phg/phg_build.c', 'phg/phg_build_calls.c',
            'phg/phg_coarse.c', 'phg/phg_comm.c',
            'phg/phg_distrib.c', 'phg/phg_gather.c', 'phg/phg_hypergraph.c',
            'phg/phg_lookup.c', 'phg/phg_match.c',
            'phg/phg_order.c', 'phg/phg_parkway.c', 'phg/phg_partition_tree.c',
            'phg/phg_patoh.c', 'phg/phg_plot.c', 'phg/phg_rdivide.c', 'phg/phg_refinement.c',
            'phg/phg_scale.c', 'phg/phg_serialpartition.c', 'phg/phg_tree.c',
            'phg/phg_two_ways.c', 'phg/phg_util.c','phg/phg_Vcycle.c',
            'phg/phg_verbose.c', 'rcb/box_assign.c', 'rcb/create_proc_list.c',
            'rcb/inertial1d.c', 'rcb/inertial2d.c',
            'rcb/inertial3d.c', 'rcb/point_assign.c', 'rcb/rcb.c', 'rcb/rcb_box.c',
            'rcb/rcb_partition_tree.c', 'rcb/rcb_util.c',
            'rcb/rib.c', 'rcb/rib_util.c',
            'rcb/shared.c', 'reftree/reftree_build.c',
            'reftree/reftree_coarse_path.c', 'reftree/reftree_hash.c',
            'reftree/reftree_part.c', 'simple/block.c', 'simple/cyclic.c', 'simple/random.c',
            'tpls/build_graph.c', 'tpls/parmetis_interface.c',
            'tpls/postprocessing.c',
            'tpls/preprocessing.c', 'tpls/scatter_graph.c',
            'tpls/third_library.c',
            'tpls/verify_graph.c', 'Utilities/Timer/timer.c',
            'Utilities/Timer/zoltan_timer.c', 'zz/murmur3.c',
            'zz/zz_back_trace.c', 'zz/zz_coord.c', 'zz/zz_gen_files.c',
            'zz/zz_hash.c','zz/zz_heap.c',
            'zz/zz_init.c', 'zz/zz_map.c', 'zz/zz_obj_list.c', 'zz/zz_rand.c',
            'zz/zz_set_fn.c', 'zz/zz_sort.c', 'zz/zz_struct.c', 'zz/zz_util.c',
            'driver/dr_dd.c', 'driver/dr_ddCPP.cpp',
            'driver/dr_elem.c', 'driver/dr_elem_util.c',
            'driver/dr_err.c',
            'driver/dr_eval.c',
            'driver/dr_gnuplot.c',
            'driver/dr_migrate.c',
            'driver/dr_input.c', 'driver/dr_loadbal.c',
            'driver/dr_setfixed.c', 'driver/dr_util.c',
            'driver/order_test.c',
            'driver/dr_par_util.c', 'driver/dr_random_io.c',
            'driver/dr_output.c', 'driver/dr_param_file.c',
            'driver/dr_maps.c', 'driver/dr_main.c',
            'driver/dr_hg_readfile.c', 'driver/dr_hg_io.c',
            'driver/dr_exoII_io.c', 'driver/dr_chaco_io.c',
            'driver/dr_mmio.c', 'driver/dr_mm_readfile.c',
            ]
others=[
    'order/hund.c', 'timer/timer_params.c',
    'tpls/scotch_interface.c',
    'driver/dr_exoII_ioCPP.cpp',
    'driver/dr_migrateCPP.cpp',
    'driver/dr_compress.c',
    'driver/dr_loadbalCPP.cpp',
    'driver/dr_mainCPP.cpp', 'driver/dr_mapsCPP.cpp',
    'driver/dr_param_fileCPP.cpp',
    'fort/cwrap.c' ]

f90_srcs= ['fdriver/fdr_chaco_io.f90', 'fdriver/fdr_const.f90', 'fdriver/fdr_input.f90', 'fdriver/fdr_loadbal.f90', 'fdriver/fdr_main.f90', 'fdriver/fdr_migrate.f90', 'fdriver/fdr_mm_io.f90', 'fdriver/fdr_param_file.f90', 'fdriver/fdr_sort.f90', 'fort/fwrap.f90', 'fort/zoltan_user_data.f90', 'fort/ztypes.f90']
