#! /bin/bash
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    PRODUCTION=0
    # Destination docs
    DEST="$CASSIOPEE/Dist/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Cassiopee"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 1 ])
then
    PRODUCTION=0
    # Destination docs
    DEST="$1/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Cassiopee"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 2 ])
then
    PRODUCTION=1
    # Destination docs
    DEST="$CASSIOPEE/WWW/cassiopee-web"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Cassiopee"
    # Destination des release notes
    DEST3="$CASSIOPEE/WWW/Main/Download"
else
    echo 'install: install in $CASSIOPEE/Dist/doc'
    echo 'install <dir>: install in directory <dir/doc>.'
    exit
fi

# Copy all docs locally
cp $CASSIOPEE/Apps/Modules/Converter/doc2/source/Internal.rst source/
cp $CASSIOPEE/Apps/Modules/Converter/doc2/source/ConverterMpi.rst source/
cp $CASSIOPEE/Apps/Modules/Converter/doc2/source/elsAProfile.rst source/
cp $CASSIOPEE/Apps/Modules/Converter/doc2/source/Converter.rst source/

cp $CASSIOPEE/Apps/Modules/Geom/doc2/source/Geom.rst source/
cp $CASSIOPEE/Apps/Modules/Compressor/doc2/source/Compressor.rst source/
cp $CASSIOPEE/Apps/Modules/Initiator/doc2/source/Initiator.rst source/
cp $CASSIOPEE/Apps/Modules/Generator/doc2/source/Generator.rst source/
cp $CASSIOPEE/Apps/Modules/Transform/doc2/source/Transform.rst source/
cp $CASSIOPEE/Apps/Modules/Dist2Walls/doc2/source/Dist2Walls.rst source/
cp $CASSIOPEE/Apps/Modules/Distributor2/doc2/source/Distributor2.rst source/
cp $CASSIOPEE/Apps/Modules/Post/doc2/source/Post.rst source/
cp $CASSIOPEE/Apps/Modules/RigidMotion/doc2/source/RigidMotion.rst source/

cp $CASSIOPEE/Apps/Modules/CPlot/doc2/source/CPlot.rst source/
cp $CASSIOPEE/Apps/Modules/CPlot/doc2/source/tkCassiopee.rst source/
cp $CASSIOPEE/Apps/Modules/Intersector/doc2/source/Intersector.rst source/

sphinx-build -b html ./source ./build
# recopie global search index, global index
sed -i 's/Internal.Converter/Converter/g' build/searchindex.js
sed -i 's/Converter.Mpi.Converter.Mpi/Converter.Mpi/g' build/searchindex.js
sed -i 's/elsAProfile.Converter/Converter/g' build/searchindex.js
sed -i 's/Converter.Converter/Converter/g' build/searchindex.js

sed -i 's/Geom.Geom/Geom/g' build/searchindex.js
sed -i 's/Compressor.Compressor/Compressor/g' build/searchindex.js
sed -i 's/Initiator.Initiator/Initiator/g' build/searchindex.js
sed -i 's/Generator.Generator/Generator/g' build/searchindex.js
sed -i 's/Transform.Transform/Transform/g' build/searchindex.js
sed -i 's/Dist2Walls.Dist2Walls/Dist2Walls/g' build/searchindex.js
sed -i 's/Distributor2.Distributor2/Distributor2/g' build/searchindex.js
sed -i 's/Post.Post/Post/g' build/searchindex.js
sed -i 's/RigidMotion.RigidMotion/RigidMotion/g' build/searchindex.js

sed -i 's/CPlot.CPlot/CPlot/g' build/searchindex.js
sed -i 's/Intersector.Intersector/Intersector/g' build/searchindex.js

cp build/searchindex.js $DEST
cp build/genindex.html $DEST
cp build/py-modindex.html $DEST
cp build/search.html $DEST
cp -r build/_sources $DEST
