#! /bin/sh
#
# Installation du module XCore
#
# Pour l'installation standard (dans $CASSIOPEE/Dist/bin/$ELSAPROD/),
# taper  : ./install
# Pour une installation dans un repertoire <rep>, taper : ./install <rep>
# Puis suivre les instructions.
#
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    if [ "$ELSAPROD" = "" ]; then
        export ELSAPROD=x86_r8
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or- '
    echo 'install <dir>: install in directory <dir>.'
    exit
fi

# Compilation et installation
which scons &>/dev/null
if [ $? -eq 0 ]; then
    if [ "$OMP_NUM_THREADS" != "" ]; then
        export SCONSOPT="-j $OMP_NUM_THREADS"
    else
        export SCONSOPT=""
    fi
    scons install prefix="$INSTALLPATH" "$SCONSOPT"
    [ $? != 0 ] && exit;
    #touch KCore/xcore.cpp
    rm -f build/lib.*/XCore/xcore.*
    python setupScons.py install --prefix="$INSTALLPATH"
else
    python setup.py install --prefix="$INSTALLPATH"
fi

# Install libxcore
python installLib.py

# Check installation
python test/t1.py
