#==============================================================================
# Fichiers c++
#==============================================================================
cpp_srcs = [
            'ch/ch_dist_graph.c', 'ch/ch_init_dist.c', 
            'ch/ch_init_dist_const.h', 'ch/ch_input_assign.c', 'ch/ch_input_const.h', 
            'ch/ch_input_geom.c', 'ch/ch_input_graph.c', 'ch/ch_input_read.c',
            'coloring/bucket.c', 'coloring/bucket.h', 'coloring/coloring.c', 
            'coloring/coloring.h', 'coloring/coloring_const.h', 
            #'coloring/color_test.c', 
            'coloring/g2l_hash.c', 'coloring/g2l_hash.h',  
]

cpp_srcs_all = ['all/all_allo.c', 'all/all_allo_const.h', 
            'ch/ch_dist_graph.c', 'ch/ch_init_dist.c', 
            'ch/ch_init_dist_const.h', 'ch/ch_input_assign.c', 'ch/ch_input_const.h', 
            'ch/ch_input_geom.c', 'ch/ch_input_graph.c', 'ch/ch_input_read.c', 
            'coloring/bucket.c', 'coloring/bucket.h', 'coloring/coloring.c', 
            'coloring/coloring.h', 'coloring/coloring_const.h', 'coloring/color_test.c', 
            'coloring/g2l_hash.c', 'coloring/g2l_hash.h', 
            'driver/dr_chaco_io.c', 'driver/dr_compress.c', 'driver/dr_compress_const.h', 
            'driver/dr_const.h', 'driver/dr_dd.c', 'driver/dr_dd.h', 'driver/dr_ddCPP.cpp', 
            'driver/dr_elem.c', 'driver/dr_elem_const.h', 'driver/dr_elem_util.c', 
            'driver/dr_elem_util_const.h', 'driver/dr_err.c', 'driver/dr_err_const.h', 
            'driver/dr_eval.c', 'driver/dr_eval_const.h', 'driver/dr_exoII_io.c', 
            'driver/dr_exoII_ioCPP.cpp', 'driver/dr_externs.h', 'driver/dr_gnuplot.c', 
            'driver/dr_hg_io.c', 'driver/dr_hg_readfile.c', 'driver/dr_hg_readfile.h', 
            'driver/dr_input.c', 'driver/dr_input_const.h', 'driver/dr_loadbal.c', 
            'driver/dr_loadbalCPP.cpp', 'driver/dr_loadbal_const.h', 'driver/dr_main.c', 
            'driver/dr_mainCPP.cpp', 'driver/dr_maps.c', 'driver/dr_mapsCPP.cpp', 
            'driver/dr_maps_const.h', 'driver/dr_migrate.c', 'driver/dr_migrateCPP.cpp', 
            'driver/dr_mmio.c', 'driver/dr_mmio.h', 'driver/dr_mm_readfile.c', 
            'driver/dr_output.c', 'driver/dr_output_const.h', 'driver/dr_param_file.c', 
            'driver/dr_param_file.h', 'driver/dr_param_fileCPP.cpp', 'driver/dr_param_fileCPP.h', 
            'driver/dr_par_util.c', 'driver/dr_par_util_const.h', 'driver/dr_random_io.c', 
            'driver/dr_setfixed.c', 'driver/dr_util.c', 'driver/dr_util_const.h', 
            'driver/order_test.c', 
            'fort/cwrap.c', 'fort/cwrap_fmangle.h', 
            'graph/graph.c', 'graph/graph.h', 'graph/graph_const.h', 'graph/graph_params.h', 
              'ha/divide_machine.c', 'ha/get_processor_name.c', 'ha/ha_const.h', 
              'ha/ha_ovis.c', 'ha/ha_ovis.h', 'hier/hier.c', 'hier/hier.h', 
              'hier/hier_free_struct.c', 'hsfc/hsfc.c', 'hsfc/hsfc.h', 'hsfc/hsfc_box_assign.c', 
              'hsfc/hsfc_const.h', 'hsfc/hsfc_hilbert.c', 'hsfc/hsfc_hilbert_const.h', 
              'hsfc/hsfc_params.h', 'hsfc/hsfc_point_assign.c', 'include/lbi_const.h', 
              'include/zoltan.h', 'include/zoltan_align.h', 'include/zoltan_comm.h', 
              'include/zoltan_comm_cpp.h', 'include/zoltan_cpp.h', 'include/zoltan_dd.h', 
              'include/zoltan_dd_cpp.h', 'include/zoltan_eval.h', 'include/zoltan_mem.h', 
              'include/zoltan_partition_tree.h', 'include/zoltan_timer.h', 'include/zoltan_timer_cpp.h', 
              'include/zoltan_types.h', 'lb/lb_balance.c', 'lb/lb_box_assign.c', 'lb/lb_const.h', 
              'lb/lb_copy.c', 'lb/lb_eval.c', 'lb/lb_free.c', 'lb/lb_init.c', 'lb/lb_init_const.h', 
              'lb/lb_invert.c', 'lb/lb_migrate.c', 'lb/lb_part2proc.c', 'lb/lb_point_assign.c', 
              'lb/lb_remap.c', 'lb/lb_set_fn.c', 'lb/lb_set_method.c', 'lb/lb_set_part_sizes.c', 
              'lb/low_mem_lb_migrate.c', 'matrix/matrix_build.c', 'matrix/matrix_distribute.c', 
              'matrix/matrix_operations.c', 'matrix/matrix_sym.c', 'matrix/matrix_utils.c', 
              'matrix/zoltan_matrix.h', 'order/hsfcOrder.c', 'order/hsfcOrder.h', 'order/hund.c', 
              'order/order.c', 'order/order_const.h', 'order/order_params.h', 'order/order_struct.c', 
              'order/order_tools.c', 'order/perm.c', 'par/par_average.c', 'par/par_average_const.h', 
              'par/par_bisect.c', 'par/par_bisect_const.h', 'par/par_const.h', 'par/par_median.c', 
              'par/par_median_const.h', 'par/par_median_randomized.c', 'par/par_stats.c', 
              'par/par_sync.c', 'par/par_tflops_special.c', 'par/par_tflops_special_const.h', 
              'params/assign_param_vals.c', 'params/bind_param.c', 'params/check_param.c', 
              'params/free_params.c', 'params/key_params.c', 'params/key_params.h', 
              'params/params_const.h', 'params/print_params.c', 'params/set_param.c', 
              'phg/phg.c', 'phg/phg.h', 'phg/phg_build.c', 'phg/phg_build_calls.c', 
              'phg/phg_coarse.c', 'phg/phg_comm.c', 'phg/phg_comm.h', 'phg/phg_const.h', 
              'phg/phg_distrib.c', 'phg/phg_distrib.h', 'phg/phg_gather.c', 'phg/phg_hypergraph.c', 
              'phg/phg_hypergraph.h', 'phg/phg_lookup.c', 'phg/phg_lookup.h', 'phg/phg_match.c', 
              'phg/phg_order.c', 'phg/phg_params.h', 'phg/phg_parkway.c', 'phg/phg_partition_tree.c', 
              'phg/phg_patoh.c', 'phg/phg_plot.c', 'phg/phg_rdivide.c', 'phg/phg_refinement.c', 
              'phg/phg_scale.c', 'phg/phg_serialpartition.c', 'phg/phg_tree.c', 'phg/phg_tree.h', 
              'phg/phg_two_ways.c', 'phg/phg_util.c', 'phg/phg_util.h', 'phg/phg_Vcycle.c', 
              'phg/phg_verbose.c', 'phg/phg_verbose.h', 'rcb/box_assign.c', 'rcb/create_proc_list.c', 
              'rcb/create_proc_list_const.h', 'rcb/inertial.h', 'rcb/inertial1d.c', 'rcb/inertial2d.c', 
              'rcb/inertial3d.c', 'rcb/point_assign.c', 'rcb/rcb.c', 'rcb/rcb.h', 'rcb/rcb_box.c', 
              'rcb/rcb_const.h', 'rcb/rcb_params.h', 'rcb/rcb_partition_tree.c', 'rcb/rcb_util.c', 
              'rcb/rib.c', 'rcb/rib.h', 'rcb/rib_const.h', 'rcb/rib_params.h', 'rcb/rib_util.c', 
              'rcb/shared.c', 'rcb/shared.h', 'reftree/reftree.h', 'reftree/reftree_build.c', 
              'reftree/reftree_coarse_path.c', 'reftree/reftree_const.h', 'reftree/reftree_hash.c', 
              'reftree/reftree_part.c', 'simple/block.c', 'simple/cyclic.c', 'simple/random.c', 
              'simple/simple_const.h', 'timer/timer_const.h', 'timer/timer_params.c', 
              'tpls/build_graph.c', 'tpls/graph_util.h', 'tpls/parmetis_interface.c', 
              'tpls/parmetis_interface.h', 'tpls/parmetis_interface_params.h', 'tpls/postprocessing.c', 
              'tpls/preprocessing.c', 'tpls/scatter_graph.c', 'tpls/scotch_interface.c', 
              'tpls/scotch_interface.h', 'tpls/scotch_interface_params.h', 'tpls/third_library.c', 
              'tpls/third_library.h', 'tpls/third_library_const.h', 'tpls/third_library_params.h', 
              'tpls/third_library_tools.h', 'tpls/verify_graph.c', 'Utilities/Timer/timer.c', 
              'Utilities/Timer/timer.h', 'Utilities/Timer/zoltan_timer.c', 'zz/murmur3.c', 
              'zz/zz_back_trace.c', 'zz/zz_const.h', 'zz/zz_coord.c', 'zz/zz_gen_files.c', 
              'zz/zz_hash.c', 'zz/zz_hash.h', 'zz/zz_heap.c', 'zz/zz_heap.h', 'zz/zz_id_const.h', 
              'zz/zz_init.c', 'zz/zz_map.c', 'zz/zz_obj_list.c', 'zz/zz_rand.c', 'zz/zz_rand.h', 
              'zz/zz_set_fn.c', 'zz/zz_sort.c', 'zz/zz_sort.h', 'zz/zz_struct.c', 'zz/zz_util.c',
              'zz/zz_util_const.h']

f90_srcs= ['fdriver/fdr_chaco_io.f90', 'fdriver/fdr_const.f90', 'fdriver/fdr_input.f90', 'fdriver/fdr_loadbal.f90', 'fdriver/fdr_main.f90', 'fdriver/fdr_migrate.f90', 'fdriver/fdr_mm_io.f90', 'fdriver/fdr_param_file.f90', 'fdriver/fdr_sort.f90', 'fort/fwrap.f90', 'fort/zoltan_user_data.f90', 'fort/ztypes.f90']
