#! /bin/sh
#
# Installation de CPlot
#
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit 1
    fi
    if [ "$ELSAPROD" = "" ]; then
        export ELSAPROD=x86_r8
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or- '
    echo 'install <dir>: install in directory <dir>.'
    exit 1
fi

if [ "$PYTHONEXE" != "" ]; then
    alias python=$PYTHONEXE
fi

# Compilation et installation
sconsf=`which scons`
which scons &>/dev/null
if [ $? -eq 0 ]; then
    if [ "$OMP_NUM_THREADS" != "" ]; then
        export SCONSOPT="-j $OMP_NUM_THREADS"
    else
        export SCONSOPT=""
    fi
    python $sconsf install prefix="$INSTALLPATH" "$SCONSOPT"
    [ $? != 0 ] && exit 1;
    #touch CPlot/cplot.cpp
    rm -f build/lib.*/CPlot/cplot.*
    rm -f build/lib.*/CPlot/cplot-*.*
    python setup.py install --prefix="$INSTALLPATH"
    [ $? != 0 ] && exit 1;
else
    python setupLegacy.py install --prefix="$INSTALLPATH"
    [ $? != 0 ] && exit 1;
fi
cp test/cplot "$INSTALLPATH"
cp test/cplot.py "$INSTALLPATH"
# Copie les applications
cp apps/*.py "$INSTALLPATH"
cp apps/cassiopee "$INSTALLPATH"
cp apps/appCassiopee "$INSTALLPATH"
cp apps/CCC "$INSTALLPATH"
cp apps/cassiopee.bat "$INSTALLPATH"
cp apps/cassiopeeRunWin32.bat "$INSTALLPATH"
cp apps/cassiopeeRunWin64.bat "$INSTALLPATH"
cp apps/validCassiopee "$INSTALLPATH"
cp apps/validCassiopee.bat "$INSTALLPATH"
cp apps/kcgnsview "$INSTALLPATH"
python installThemes.py

# Test l'installation
python test/t1.py
