#! /bin/sh
echo 'Installing Connector tests and doc'
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    PRODUCTION=0
    # Destination docs
    DEST="$CASSIOPEE/Dist/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Connector"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 1 ])
then
    PRODUCTION=0
    # Destination docs
    DEST="$1/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Connector"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 2 ])
then
    PRODUCTION=1
    # Destination docs
    DEST="$CASSIOPEE/WWW/cassiopee-web"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Connector"
    # Destination des release notes
    DEST3="$CASSIOPEE/WWW/Main/Download"
else
    echo 'install: install in $CASSIOPEE/Dist/doc'
    echo 'install <dir>: install in directory <dir/doc>.'
    exit
fi

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi
    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Apps/Modules/Connector/test Examples/Connector
fi
cd ..

# Build html
sphinx-build -b html ./source ./build
if ([ $PRODUCTION -eq 1 ])
then
# Build pdf
    sphinx-build -b latex ./source ./build
    cd build
    pdflatex Connector
    #pdflatex ConnectorMpi
    #pdflatex OversetData
    #pdflatex OversetDataElsA
  cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    #taghtml build/ConnectorMpi.html
    #sed -i 's/Connector.Mpi.Connector.Mpi/Connector.Mpi/g' build/ConnectorMpi.html
    #sed -i 's/Connector.pdf/ConnectorMpi.pdf/g' build/ConnectorMpi.html
    #cp build/ConnectorMpi.html $DEST
    #taghtml build/OversetData.html
    #sed -i 's/OversetData.Connector/Connector/g' build/OversetData.html
    #sed -i 's/Connector.pdf/OversetData.pdf/g' build/OversetData.html
    #taghtml build/OversetData.html
    #taghtml build/OversetDataElsA.html
    #sed -i 's/OversetDataElsA.Connector/Connector/g' build/OversetDataElsA.html
    #sed -i 's/Connector.pdf/OversetDataElsA.pdf/g' build/OversetDataElsA.html
    #taghtml build/OversetDataElsA.html
    sed -i 's/Connector.Connector/Connector/g' build/Connector.html    
    sed -i 's/Connector.Connector/Connector/g' build/Connector.html
    cp build/Connector.html $DEST
    cp build/Connector.pdf $DEST
    #cp build/ConnectorMpi.pdf $DEST
    #cp build/OversetData.pdf $DEST
    #cp build/OversetDataElsA.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../Connector/Connector.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='Connector-'$version1'.txt'
    cp Connector.txt $DEST3/$v
fi
