LIBNAME = ConnectorF
SOURCEF90 = 
SOURCEF77 =\
CompMotionCentersF.for\
CompMotionCentersEXF.for\
BlkAdjustCellNatureFieldF.for\
MaskSearchBlankedNodesXF.for\
MaskSearchBlankedNodesX2DF.for\
MaskSearchBlankedNodesXDF.for\
MaskSearchBlankedNodesXD2DF.for\
MaskSearchBlankedCellsX2DF.for\
MaskSearchBlankedCellsXF.for\
MaskSearchBlankedCellsX12DF.for\
MaskSearchBlankedCellsX1F.for\
MaskSearchBlankedCellsX22DF.for\
MaskSearchBlankedCellsX2F.for\
MaskSearchBlankedCellsXDF.for\
MaskSearchBlankedCellsXD2DF.for\
MaskSearchBlankedCellsXD2F.for\
MaskSearchBlankedCellsXD22DF.for\
MaskSearchBlankedCellsXD1F.for\
MaskSearchBlankedCellsXD12DF.for\
MaskSearchBlankedCellsUnstrXF.for\
MaskSearchBlankedCellsUnstrXDF.for\
MaskSearchBlankedCellsUnstrX2F.for
include ../Make.inc
