#! /bin/bash
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    PRODUCTION=0
    # Destination docs
    DEST="$CASSIOPEE/Dist/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Cassiopee"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 1 ])
then
    PRODUCTION=0
    # Destination docs
    DEST="$1/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Cassiopee"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 2 ])
then
    PRODUCTION=1
    # Destination docs
    DEST="$CASSIOPEE/WWW/cassiopee-web"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Cassiopee"
    # Destination des release notes
    DEST3="$CASSIOPEE/WWW/Main/Download"
else
    echo 'install: install in $CASSIOPEE/Dist/doc'
    echo 'install <dir>: install in directory <dir/doc>.'
    exit
fi

# do nothing for now
