#! /bin/bash
# Lancement de python en parallele
# kpython -n 2 script.py: lance 2 process, choisit le nbre de threads en fonction de la ressource
# kpython -n2 -t4 script.py: lance 2 process avec 4 threads chacuns
# kpython -a "env::" -n2 script.py: lance mpirun avec une option supplementaire
if ([ $# -eq 0 ])
then
    echo 'kpython -n 5 -t 2 script.py'
    exit 1
fi

# OMP_NUM_THREADS init
if [ -z "$OMP_NUM_THREADS" ]
then
    OMPNUMTHREADSINIT=$OMP_NUM_THREADS
else
    OMPNUMTHREADSINIT=1    
fi

# Ressources
ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
if [ -z "$ncpu" ]
then
    ncpu=$OMP_NUM_THREADS
else
    ncpu=$((ncpu + 1 ))    
fi

if [ -z "$ELSAPROD" ]
then
    ELSAPROD=""
fi

NPROCS=0
NTHREADS=0
ARGS=""
while getopts hn:t:a: OPTION
do
     case $OPTION in
         h)
             echo 'kpython -n 5 -t 2 script.py'      
             exit 1
             ;;
         n)
             NPROCS=$OPTARG
             ;;
         t)
             NTHREADS=$OPTARG
             ;;
         a)
             ARGS=$OPTARG
             ;;
     esac
done
shift $((OPTIND-1))
SCRIPT=$*

if test $NTHREADS -eq 0
then
    NTHREADS=`expr $ncpu / $NPROCS`
fi
echo 'Running '$SCRIPT' with Nprocs='$NPROCS' and Nthreads='$NTHREADS

if test $NPROCS -eq 0
then
    export MPIRUN=0
    export OMP_NUM_THREADS=$NTHREADS
    python $SCRIPT
    export OMP_NUM_THREADS=$OMPNUMTHREADSINIT
    unset MPIRUN
else
    export MPIRUN=1
    export OMP_NUM_THREADS=$NTHREADS
    if [ $ELSAPROD == 'x86_r8' ] # eos
    then
        set -x
        # openMpi
        #mpirun $ARGS -x OMP_NUM_THREADS=$NTHREADS -np $NPROCS python $SCRIPT $NPROCS
        # intelMpi
        mpirun $ARGS -n $NPROCS -genv OMP_NUM_THREADS=$NTHREADS -l python $SCRIPT $NPROCS
        set +x
    elif [ $ELSAPROD == 'aus_r8' ] # austri
    then
        set -x
        # intelMpi
        mpirun $ARGS -n $NPROCS -genv OMP_NUM_THREADS=$NTHREADS -l python $SCRIPT $NPROCS
        set +x
    elif [ $ELSAPROD == 'sat_r8' ] # sator
    then
        set -x
        # intelMpi
        mpirun $ARGS -n $NPROCS -genv OMP_NUM_THREADS=$NTHREADS -l python $SCRIPT $NPROCS
        set +x
    elif [ $ELSAPROD == 'stv_r8' ] # stelvio
    then
        set -x
        # intelMpi
        mptrun $ARGS -omp $NTHREADS -np $NPROCS python $SCRIPT $NPROCS
        set +x
    elif [ $ELSAPROD == 'msys64' ] # MSYS 2 With Win64 production
    then
        set -x
	# MSMPI
	mpiexec $ARGS -np $NPROCS python $SCRIPT $NPROCS
        set +x
    else
        set -x
        mpirun $ARGS -np $NPROCS python $SCRIPT $NPROCS
        set +x
    fi
    unset MPIRUN
    export OMP_NUM_THREADS=$OMPNUMTHREADSINIT
fi
