#! /bin/sh
# *Cassiopee* machine specific (local) variables

# Preliminary checks
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

# Environment
ulimit -s unlimited

# Compilation on different machines:
# cephee: x86 processors, intel compilers -> cp
# Linux ubuntu: distribution Linux Ubuntu, g++, gfortran -> ub
# stelvio: x86 processors, intel compilers -> stv

# Detect machine (shortest first)
KC=`uname -n`
MAC0=$(echo $KC | grep 'n'); if [ "$MAC0" != "" ]; then export MAC="sator_brw"; fi
MAC0=$(echo $KC | grep 'ld'); if [ "$MAC0" != "" ]; then export MAC="ld"; fi
MAC0=$(echo $KC | grep 'clausius'); if [ "$MAC0" != "" ]; then export MAC="ld"; fi
MAC0=$(echo $KC | grep 'ubuntu'); if [ "$MAC0" != "" ]; then export MAC="ubuntu"; fi
MAC0=$(echo $KC | grep 'visio'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'austri'); if [ "$MAC0" != "" ]; then export MAC="austri"; fi
MAC0=$(echo $KC | grep 'celeste'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'visung'); if [ "$MAC0" != "" ]; then export MAC="visung"; fi
MAC0=$(echo $KC | grep 'giulia'); if [ "$MAC0" != "" ]; then export MAC="giulia"; fi
MAC0=$(echo $KC | grep 'sator'); if [ "$MAC0" != "" ]; then export MAC="sator_brw"; fi
MAC0=$(echo $KC | grep 'jean-zay'); if [ "$MAC0" != "" ]; then export MAC="jean-zay"; fi
MAC0=$(echo $KC | grep 'spiro'); if [ "$MAC0" != "" ]; then export MAC="spiro_el8"; fi
MAC0=$(echo $KC | grep 'f0'); if [ "$MAC0" != "" ]; then export MAC="juno"; fi
MAC0=$(echo $KC | grep 'n0'); if [ "$MAC0" != "" ]; then export MAC="juno"; fi
MAC0=$(echo $KC | grep 'v0'); if [ "$MAC0" != "" ]; then export MAC="juno"; fi
MAC0=$(echo $KC | grep 'cobalt'); if [ "$MAC0" != "" ]; then export MAC="cobalt"; fi
MAC0=$(echo $KC | grep 'irene'); if [ "$MAC0" != "" ]; then export MAC="irene"; fi
MAC0=$(echo $KC | grep 'jean-zay'); if [ "$MAC0" != "" ]; then export MAC="jean-zay"; fi
MAC0=$(echo $KC | grep 'node6.cluster'); if [ "$MAC0" != "" ]; then export MAC="macosx"; fi
MAC0=$(echo $KC | grep 'topaze'); if [ "$MAC0" != "" ]; then export MAC="topaze"; fi
MAC0=$(echo $KC | grep 'Aryen'); if [ "$MAC0" != "" ]; then export MAC="aryen"; fi
MAC0=$(echo $KC | grep 'WDAAA161Z'); if [ "$MAC0" != "" ]; then export MAC="WDAAA161Z"; fi

# Detect the type of integer that is used
INTTYPE=""
if [[ $MACHINE == *_i8 ]]; then
    export MAC=${MACHINE%"_i8"}
    INTTYPE="_i8"
elif [[ "$MACHINE" == "i8" ]]; then
    INTTYPE="_i8"
elif [[ "$MACHINE" != "" ]]; then
    export MAC=$MACHINE
fi
#echo 'Cassiopee :: MACHINE NAME::'$MAC, $KC, $MACHINE

# ----------------------------- Prods ------------------------------------------
if [ "$MAC" = "ld_eos8" ]; then
#------------------------------- ld centos 8 + python 3 -----------------------------------
    export ELSAPROD=eos8_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    #module unload $(module -t list 2>&1 | grep -i intel)
    #module purge
    module unload intel/19.0.5
    module unload impi/19.0.5
    #module load oce/7.5.0-gnu831
    module load occt/7.6.1-gnu831
    module load python/3.6.1-gnu831
    #module load python/3.10.8-gnu831
    module load intel/21.2.0
    #module load impi/21.2.0
    module load hdf5/1.8.17-intel2120
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo | tail -1 | cut -f2 -d: )
    ncpu=$((ncpu + 1))
    export OMP_NUM_THREADS=$ncpu

elif [ "$MAC" = "ld" ]; then
#------------------------------- ld centos 8 + python 3 -----------------------------------
    export ELSAPROD=ld
    export ELSAPROD=$ELSAPROD$INTTYPE
    module purge
    module load occt/7.6.1-gnu831
    module load python/3.8.14-gnu831
    #module load intel/21.2.0
    module load gcc/10.2.0
    module load lapack/3.9.1-gnu831
    module load hdf5/1.10.5-gnu831-ompi405
    unset I_MPI_PMI_LIBRARY
    export PRODMODE=1
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo | tail -1 | cut -f2 -d: )
    ncpu=$((ncpu + 1))
    export OMP_NUM_THREADS=$ncpu

elif [ "$MAC" = "ld_python2" ]; then
#------------------------------- ld centos 7 -----------------------------------
    export ELSAPROD=x86_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    module unload $(module -t list 2>&1 | grep -i intel)
    module load python/2.7.8
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.8
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo | tail -1 | cut -f2 -d: )
    ncpu=$((ncpu + 1))
    export OMP_NUM_THREADS=$ncpu
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3],explicit"
    # chemin de mpirun (forced)
    # Pour utilisation MKL+numpy
    #export LD_PRELOAD=/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_avx2.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_def.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_core.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_lp64.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_thread.so:/opt/tools/intel/studio/2017/lib/intel64/libiomp5.so

elif [ "$MAC" = "macosx" ]; then
#----------------------------- Mac OSX-----------------------------------------
    export ELSAPROD=macosx
    export ELSAPROD=$ELSAPROD$INTTYPE
    export OMP_NUM_THREADS=2
    export MACOSX_DEPLOYMENT_TARGET=10.10
    unset BUNDLE
    export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATHL

elif [ "$MAC" = "mangrove" ]; then
#-------------------------------- mangrove -------------------------------------
    export ELSAPROD=man_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    export OMP_NUM_THREADS=4

elif [ "$MAC" = "ubuntu" ]; then
#-------------------------------- ubuntu --------------------------------------
    export ELSAPROD=ub_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    export OMP_NUM_THREADS=2

elif [ "$MAC" = "visio" ]; then
#----------------------------- visio -----------------------------------------
    export ELSAPROD=vis_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    . /etc/profile.d/modules-dri.sh
    module load subversion/1.7.6
    module load python/2.7.8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/4.8.1
    module load intel/17.0.4
    module load impi/17
    # Nombre de threads
    export OMP_NUM_THREADS=16

elif [ "$MAC" = "spiro_gcc" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_gcc
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    module purge
    module load occt/7.6.1-gnu831
    #module load python/3.6.1-gnu831
    module load python/3.10.8-gnu831
    module load gcc/10.2.0
    module load hdf5/1.10.5-gnu831-ompi405
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=1
    export OMP_PLACES=cores
    unset $(env | grep SLURM | cut -d'=' -f 1)

elif [ "$MAC" = "visung" ]; then
#----------------------------- visung -----------------------------------------
    export ELSAPROD=visung_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=72
    . /etc/profile.d/modules-onera.sh
    module purge
    module load subversion
    module load occt/7.6.1-gnu831
    module load python/3.8.14-gnu831
    #module load intel/21.2.0
    module load gcc/10.2.0
    module load hdf5/1.10.5-gnu831-ompi405
    module load lapack/3.9.1-gnu831
    export PRODMODE=1
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "visung_el8" ]; then
#----------------------------- visung -----------------------------------------
    export ELSAPROD=visung_el8
    export ELSAPROD=$ELSAPROD$INTTYPE
    #. /etc/profile.d/modules-dri.sh
    module purge
    module load subversion
    module load python/3.7.4-intel2120
    module load intel/21.2.0
    module load hdf5/1.10.5-intel2120-impi
    module load occt/7.6.1-gnu831
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export OMP_NUM_THREADS=72
    #export PRODMODE=1
    #export PIP_DISABLE_PIP_VERSION_CHECK=1
    unset I_MPI_PMI_LIBRARY

elif [ "$MAC" = "austri" ]; then
#----------------------------- austri -----------------------------------------
    export ELSAPROD=aus_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,2,4,6,8,10,12,14,16,18,20,22,1,3,5,7,9,11,13,15,17,19,21,23],explicit"
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11],explicit"
    # modules
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/4.9
    module load intel/17.0.4
    module load impi/17 # very bad install
    module unload impi/17
    module load hdf5/1.8.8-intel-11

elif [ "$MAC" = "giulia" ]; then
#----------------------------- giulia -----------------------------------------
    export ELSAPROD=giu_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    # modules
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/5.2
    module load python/2.7.8
    module load intel/17.0.4
    module load impi/16
    module unload hdf5/1.8.8
    module load hdf5/1.8.8-intel-16.impi
    #module purge
    #module load   python/2.7.8
    #source /stck/nalferez/intel/parallel_studio_xe_2018/psxevars.sh
    #export PATH=/stck5/nalferez/intel/2018update2/PythonIntel/intelpython2/bin/:/usr/local/python-gnu-2.7.8/bin/:$PATH

elif [ "$MAC" = "cobalt" ]; then
#-------------------------------- cobalt -----------------------------------------
    export ELSAPROD=cob_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=28

    # modules
    module purge
    module load intel/17.0.6.256
    module load mpi/openmpi
    module load python/2.7.14
    module load hdf5/1.8.20
    module load libosmesa/10.6.5
    module load libpng/1.6.23

elif [ "$MAC" = "tgcc_irene" ]; then
#-------------------------------- irene -----------------------------------------
    export ELSAPROD=irene_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    echo 'TGCC_IRENE SH_CASSIOPEE_LOCAL _v2'
    # modules
    module purge
    module load intel/20
    module load mpi/openmpi
    module load python/2.7.14
    module load hdf5/1.8.20
    #module load scons/3.0.1

elif [ "$MAC" = "jean-zay" ]; then
#-------------------------------- jean-zay -----------------------------------------
    export ELSAPROD=jz_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    module load python/3.8.2
    module load gcc/9.1.0-cuda-openacc
    module load openmpi/4.1.1-cuda
    module load hdf5/1.10.5
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    # Number of threads
    export OMP_NUM_THREADS=28

elif [ "$MAC" = "spiro" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    #module load CFD/4.0-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8
    module load subversion/1.14.1-gnu830
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_sky" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_sky_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    #module load CFD/4.0-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_cas" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_cas_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    #module load CFD/4.0-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_amdRM" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_amdrm_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=32
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_amdNP" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_amdnp_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=32
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_socle6" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_socle_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    #. /usr/local/Modules/init/bash
    module purge
    module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load subversion/1.14.1-gnu831
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=1

elif [ "$MAC" = "spiro_sonics" ]; then
#----------------------------- spiro sonics -----------------------------------------
    export ELSAPROD=linux64
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /etc/profile.d/modules-onera.sh
    module purge
    source /scratchm/sonics/dist/spiro-el8.sh --compiler=intel@2022 --mpi=impi
    module load emacs
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_python2" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    #module load CFD/4.0-intel-17.impi
    module load python/2.7.8-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17

elif [ "$MAC" = "spiro_anaconda" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_acda
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    #module load CFD/4.0-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module unload hdf5/1.8.8
    module load hdf5/1.8.17-intel-17
    module load anaconda/2021.05
    module load subversion/1.14.1-gnu830
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_el8" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_el8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    source /opt/tools/Modules/init/bash
    module purge
    module load socle-cfd/5.0-intel2120-impi
    #module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    alias inspxe-cl="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect mi3 -- python3 "
    alias inspxe-cl2="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect ti3 -- python3 "
    alias inspxe-gui="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-gui result"
    alias vtune="vtune -collect hotspots -result-dir result -quiet"
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=0
    unset I_MPI_FABRICS_LIST
    unset I_MPI_FABRICS
    unset I_MPI_TCP_NETMASK
    unset I_MPI_PMI_LIBRARY
    unset $(env | grep SLURM | cut -d'=' -f 1)
    export OMP_PLACES=cores

elif [ "$MAC" = "spiro_intel" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_intel
    export ELSAPROD=$ELSAPROD$INTTYPE
    echo $ELSAPROD
    # Nbre de threads
    export OMP_NUM_THREADS=24
    module purge
    module load intel/19.0.5
    module load occt/7.6.1-gnu831
    module load python/3.6.1-gnu831
    module load hdf5/1.10.3-intel1905
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_coda" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_coda
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    module purge
    source /stck/rhea/dist/spiro_v2023_10/source.sh --env coda_dev --compiler gcc@10 --mpi openmpi
    #module load hdf5/1.10.5-gnu831-ompi405
    module load subversion/1.14.1-gnu831
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_arm" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_arm
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=56
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "spiro_pgi" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_pgi
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=24
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    module purge
    module load python/3.6.1-gnu831
    module load nvhpc/22.2-gnu831-full
    module load subversion/1.14.1-gnu831

elif [ "$MAC" = "juno" ]; then
#----------------------------- juno -----------------------------------------
    export ELSAPROD=juno
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=48
    # modules
    source /opt/tools/Modules/init/bash
    module purge
    module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    alias inspxe-cl="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect mi3 -- python3 "
    alias inspxe-cl2="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect ti3 -- python3 "
    alias inspxe-gui="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-gui result"
    alias vtune="vtune -collect hotspots -result-dir result -quiet"
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    unset I_MPI_FABRICS_LIST
    unset I_MPI_FABRICS
    unset I_MPI_TCP_NETMASK
    unset I_MPI_PMI_LIBRARY
    unset $(env | grep SLURM | cut -d'=' -f 1)
    export OMP_PLACES=cores

elif [ "$MAC" = "juno_gcc" ]; then
#----------------------------- juno -----------------------------------------
    export ELSAPROD=juno_gcc
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=48
    # modules
    source /opt/tools/Modules/init/bash
    module purge
    #module load gcc/10.2.0
    #module load python/3.10.8-gnu831
    #module load hdf5/1.10.5-gnu831-ompi405
    module load lapack/3.9.1-gnu831
    module load occt/7.6.1-gnu831
    module load socle-cfd/7.0-gnu850-ompi502
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    unset $(env | grep SLURM | cut -d'=' -f 1)
    #export OMP_PLACES=cores

elif [ "$MAC" = "juno_coda" ]; then
#----------------------------- juno -----------------------------------------
    export ELSAPROD=juno_coda
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=48
    # modules
    module purge
    source /stck/rhea/dist/juno_v2024_02_python3108/source.sh --env coda_dev --compiler gcc@10 --mpi openmpi
    module load subversion/1.14.1-gnu831
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=1

elif [ "$MAC" = "sator_brw" ]; then
#----------------------------- sator for broadwell -----------------------------------------
    export ELSAPROD=sat_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    . /etc/profile.d/module.sh
    module purge
    module load python/3.7.4-intel2120
    module load hdf5/1.10.5-intel2120-impi
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    # Other aliases
    alias ffmpeg=/opt/tools/altair/2021.1/altair/hwdesktop/hw/bin/linux64/ffmpeg
    # Number of threads
    export OMP_NUM_THREADS=28
    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"
    #export KMP_AFFINITY="scatter,1,0,granularity=fine,verbose"

elif [ "$MAC" = "topaze" ]; then
#----------------------------- topaze ccrt proc amd milan ---------------------------------------
    export ELSAPROD=topaze_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    . /etc/profile.d/module.sh
    module purge
    module load intel/20 mpi/openmpi/4 flavor/hdf5/parallel hdf5/1.8.20
    module load python3/3.8.10
    module load scons/4.4.0
    export LD_PRELOAD=/ccc/products2/icc-20.0.0/Rhel_8__x86_64/system/default/compilers_and_libraries_2020.0.166/linux/compiler/lib/intel64_lin/libiomp5.so
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    # Number of threads
    export OMP_NUM_THREADS=64
    export KMP_AFFINITY=verbose
    export OMP_PLACES=cores

elif [ "$MAC" = "sator_sky" ]; then
#----------------------------- sator skylake ---------------------------------------
    export ELSAPROD=sat_sky_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    . /etc/profile.d/module.sh
    module purge
    #module load socle-cfd/5.0-intel2120-impi
    module load python/3.7.4-intel2120
    module load hdf5/1.10.5-intel2120-impi
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    # Number of threads
    export OMP_NUM_THREADS=44

elif [ "$MAC" = "sator_cas" ]; then
    #----------------------------- sator for cascade ---------------------------------------
    export ELSAPROD=sat_cas_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=48
    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"
    . /etc/profile.d/module.sh
    module purge
    #module load socle-cfd/5.0-intel2120-impi
    module load python/3.7.4-intel2120
    module load hdf5/1.10.5-intel2120-impi
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    unset I_MPI_PMI_LIBRARY
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    # Other aliases
    alias ffmpeg=/opt/tools/altair/2021.1/altair/hwdesktop/hw/bin/linux64/ffmpeg

elif [ "$MAC" = "sator_sph" ]; then
    #----------------------------- sator for saphire ---------------------------------------
    export ELSAPROD=sat_sph
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=48
    module purge
    module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load emacs/27.2-gnu831
    unset I_MPI_FABRICS_LIST
    unset I_MPI_FABRICS
    unset I_MPI_PMI_LIBRARY
    unset I_MPI_TCP_NETMASK
    export OMP_PLACES=cores
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1

elif [ "$MAC" = "jean-zay" ]; then
#-----------------------------jean-zay IDRIS  ---------------------------------------
    export ELSAPROD=jz_r8
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=40
    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"

    # modules
    #. /etc/profile.d/module.sh
    module load intel-compilers/19.1.3
    module load intel-mpi/2019.9
    module load python/3.7.10
    module load hdf5/1.12.0
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python

elif [ "$MAC" = "aryen" ]; then
#----------------------------- Aryen msys2  ---------------------------------------
    export ELSAPROD=win64
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=2
    # modules
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=1

elif [ "$MAC" = "WDAAA161Z" ]; then
#----------------------------- msys64 "AlainRE"  ---------------------------------------
    export ELSAPROD=win64
    export ELSAPROD=$ELSAPROD$INTTYPE
    # Nbre de threads
    export OMP_NUM_THREADS=4
    # modules
    export PYTHONEXE=python3
    python() { python3 "$@"; }
    export -f python
    export PRODMODE=1
fi


#-------------------------- Common to all prods --------------------------------
# Chemin de l'executable python
if ! [ -z $PATHL ]; then
    OLD_PATHL=$PATHL
    OLD_LD_LIBRARY_PATHL=$LD_LIBRARY_PATHL
    OLD_PYTHONPATHL=$PYTHONPATHL
fi
pyversion="python"`python -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`
export PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin
export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
export PYTHONPATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/"$pyversion"/site-packages
    
if ! [ -z $OLD_PATHL ]; then
    # Remove all occurences of old paths
    PATH="${PATH//$OLD_PATHL/}"
    LD_LIBRARY_PATH="${LD_LIBRARY_PATH//$OLD_LD_LIBRARY_PATHL/}"
    PYTHONPATH="${PYTHONPATH//$OLD_PYTHONPATHL/}"
    
    # Remove empty paths
    PATH=$(echo "$PATH" | sed 's/::\+/:/g; s/^:\|:$//g')
    LD_LIBRARY_PATH=$(echo "$LD_LIBRARY_PATH" | sed 's/::\+/:/g; s/^:\|:$//g')
    PYTHONPATH=$(echo "$PYTHONPATH" | sed 's/::\+/:/g; s/^:\|:$//g')
fi

# Prefix with new paths
export PATH=$PATHL:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATHL:$LD_LIBRARY_PATH
export PYTHONPATH=$PYTHONPATHL:$PYTHONPATH

echo $ELSAPROD' environment set.'
