#! /bin/sh
# *Cassiopee* machine specific (local) variables

# Preliminary checks
unset ELSAPROD
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

# Environment
[ "$(ulimit -Hs)" = "unlimited" ] && ulimit -s unlimited

# Compilation on different machines:
EXT=""
if [ -n "$MACHINE" ]; then
    # Detect MAC environement from MACHINE
    INTTYPE=""
    DBGMODE=""
    BRANCHNAME=""
    MACHINETMP=$MACHINE
    if [ "${MACHINETMP#*_DBG*}" != "$MACHINETMP" ]; then
        MACHINETMP="${MACHINETMP//_DBG/}"
        DBGMODE="_DBG"
    fi

    if [ "${MACHINETMP#*_i8*}" != "$MACHINETMP" ]; then
        MACHINETMP="${MACHINETMP//_i8/}"
        INTTYPE="_i8"
    fi
    
    if [ "${MACHINETMP#*_b-*}" != "$MACHINETMP" ]; then
        BRANCHNAME=${MACHINETMP#*_b-$BRANCHNAME}
        BRANCHNAME=${BRANCHNAME%_*}
        MACHINETMP="${MACHINETMP//_b-$BRANCHNAME/}"
        MACHINETMP=${MACHINETMP%_}
        BRANCHNAME="_$BRANCHNAME"
    fi
    
    export MAC=$MACHINETMP
    EXT=$BRANCHNAME$INTTYPE$DBGMODE
    unset MACHINETMP BRANCHNAME INTTYPE DBGMODE
else
    # Detect machine by uname (longest first)
    KC=$(uname -n)
    for pattern in \
      "WDAAA161Z:WDAAA161Z" \
      "atlas:atlas" \
      "topaze:topaze" \
      "node6.cluster:macosx" \
      "jean-zay:jean_zay" \
      "irene:irene" \
      "cobalt:cobalt" \
      "spiro:spiro" \
      "sator:sator_sph" \
      "giulia:giulia" \
      "visung:visung" \
      "celeste:visio" \
      "visio:visio" \
      "ubuntu:ubuntu" \
      "clausius:ld" \
      "fv-az:azure" \
      "v0:juno" \
      "b0:juno" \
      "n0:juno" \
      "f0:juno" \
      "ld:ld" \
      "n:sator_sph"
    do
      key=${pattern%%:*}; val=${pattern#*:}
      if echo "$KC" | grep -q "$key"; then
        export MAC="$val"
        break
      fi
    done
fi

if [ -z "$MAC" ]; then
    echo 'Your machine is not known by uname. Try to set MACHINE.'
    return 1
fi

# ----------------------------- Prods ------------------------------------------
if [ -f "$CASSIOPEE/Cassiopee/Envs/sh_Cassiopee_user" ]; then
    . "$CASSIOPEE/Cassiopee/Envs/sh_Cassiopee_user"
fi

if [ -z $ELSAPROD ]; then
if [ "$MAC" = "ld" ]; then
#------------------------------- ld rocky 8 + python 3 -----------------------------------
    export ELSAPROD=ld
    export ELSAPROD=$ELSAPROD$EXT
    . /etc/profile.d/modules-onera.sh
    module purge
    module load occt/7.6.1-gnu831
    module load netcdf/4.8.0-gnu831
    module load python/3.8.14-gnu831
    module load gcc/10.2.0
    module load lapack/3.9.1-gnu831
    #module load hdf5/1.10.5-gnu831-ompi405
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export PYTHONEXE=python3
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo | tail -1 | cut -f2 -d: )
    ncpu=$((ncpu + 1))
    export OMP_NUM_THREADS=$ncpu
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/opt/tools/gcc/10.2.0-gnu831/lib64/libasan.so

elif [ "$MAC" = "ld_spack1" ]; then
#------------------------------- ld spack1 + python 3.10 ----------------------------------
    export ELSAPROD=ld_spack1
    export ELSAPROD=$ELSAPROD$EXT
    . /etc/profile.d/modules-onera.sh
    module purge
    export PATH="/tmp_user/ldaaa2323z/benoit/spack_installed/install/bin":"/tmp_user/ldaaa2323z/benoit/spack/var/spack/environments/test/.spack-env/view/bin":"/tmp_user/ldaaa2323z/benoit/spack/bin":"/usr/local/sbin":"/usr/bin:/usr/sbin:/usr/local/bin"
    export LD_LIBRARY_PATH=/tmp_user/ldaaa2323z/benoit/spack_installed/install/lib:/tmp_user/ldaaa2323z/benoit/spack_installed/install/lib64:/tmp_user/ldaaa2323z/benoit/spack/var/spack/environments/test/.spack-env/view/lib:/tmp_user/ldaaa2323z/benoit/spack/var/spack/environments/test/.spack-env/view/lib64
    export PYTHONPATH=/tmp_user/ldaaa2323z/benoit/spack_installed/install/lib/python3.10/site-packages:/tmp_user/ldaaa2323z/benoit/spack/var/spack/environments/test/.spack-env/view/lib/python3.10/site-packages
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export PYTHONEXE=python3
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo | tail -1 | cut -f2 -d: )
    ncpu=$((ncpu + 1))
    export OMP_NUM_THREADS=$ncpu

elif [ "$MAC" = "ld_spack2" ]; then
#------------------------------- ld spack2 + python 3.9 ----------------------------------
    export ELSAPROD=ld_spack2
    export ELSAPROD=$ELSAPROD$EXT
    . /etc/profile.d/modules-onera.sh
    module purge
    export PATH="/tmp_user/ldaaa2323z/benoit/spack_installed/install2/bin":"/tmp_user/ldaaa2323z/benoit/spack/var/spack/environments/dassault/.spack-env/view/bin":"/tmp_user/ldaaa2323z/benoit/spack/bin":"/usr/local/sbin":"/usr/bin:/usr/sbin:/usr/local/bin"
    export LD_LIBRARY_PATH=/tmp_user/ldaaa2323z/benoit/spack_installed/install2/compiler/2021.4.0/linux/lib:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/compiler/2021.4.0/linux/lib/x64:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/compiler/2021.4.0/linux/lib/emu:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/compiler/2021.4.0/linux/lib/oclfpga/host/linux64/lib:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/compiler/2021.4.0/linux/lib/oclfpga/linux64/lib:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/compiler/2021.4.0/linux/compiler/lib/intel64_lin:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/mpi/2021.4.0/libfabric/lib:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/mpi/2021.4.0/lib/release:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/mpi/2021.4.0/lib:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/lib:/tmp_user/ldaaa2323z/benoit/spack_installed/install2/lib64
    export PYTHONPATH=/tmp_user/ldaaa2323z/benoit/spack_installed/install2/lib/python3.9/site-packages:/tmp_user/ldaaa2323z/benoit/spack/var/spack/environments/dassault/.spack-env/view/lib/python3.9/site-packages
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export PYTHONEXE=python3
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo | tail -1 | cut -f2 -d: )
    ncpu=$((ncpu + 1))
    export OMP_NUM_THREADS=$ncpu
    
elif [ "$MAC" = "macosx" ]; then
#----------------------------- Mac OSX-----------------------------------------
    export ELSAPROD=macosx
    export ELSAPROD=$ELSAPROD$EXT
    export OMP_NUM_THREADS=2
    export MACOSX_DEPLOYMENT_TARGET=10.10
    unset BUNDLE
    export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATHL

elif [ "$MAC" = "ubuntu" ]; then
#-------------------------------- ubuntu --------------------------------------
    export ELSAPROD=ubuntu
    export ELSAPROD=$ELSAPROD$EXT
    export OMP_NUM_THREADS=4
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/usr/lib/gcc/x86_64-linux-gnu/13/libasan.so
    ulimit -s 8192 # for ASAN

elif [ "$MAC" = "ubuntu-jax" ]; then
#-------------------------------- ubuntu --------------------------------------
    export ELSAPROD=ubuntu
    export ELSAPROD=$ELSAPROD$EXT
    export OMP_NUM_THREADS=4
    export PYTHONEXE=python3
    export PRODMODE=0
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/usr/lib/gcc/x86_64-linux-gnu/13/libasan.so
    ulimit -s 8192 # for ASAN
    source $CASSIOPEE/../JSolve/jax-env/bin/activate # all must be pip installed

elif [ "$MAC" = "azure" ]; then
#------------------------ azure: Centos7 - github actions ----------------------
    export ELSAPROD=azure
    export ELSAPROD=$ELSAPROD$EXT
    export OMP_NUM_THREADS=4
    export PYTHONEXE=python3
    export PRODMODE=2
    export PIP_DISABLE_PIP_VERSION_CHECK=1

elif [ "$MAC" = "linux" ]; then
#------------------------ generic linux --------------------------------------
    export ELSAPROD=linux
    export ELSAPROD=$ELSAPROD$EXT
    export OMP_NUM_THREADS=4
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1

elif [ "$MAC" = "visio" ]; then
#----------------------------- visio -----------------------------------------
    export ELSAPROD=visio
    export ELSAPROD=$ELSAPROD$EXT
    . /etc/profile.d/modules-dri.sh
    module purge
    module load python/3.6.1
    module load gcc/4.8.1
    module load intel/17.0.4
    module load impi/17
    export OMP_NUM_THREADS=16
    export PYTHONEXE=python3
    export PRODMODE=1
    
elif [ "$MAC" = "visung_gcc" ]; then
#----------------------------- visung_gcc -------------------------------------
    export ELSAPROD=visung_gcc
    export ELSAPROD=$ELSAPROD$EXT
    . /etc/profile.d/modules-onera.sh
    module purge
    module load lapack/3.9.1-gnu831
    module load occt/7.6.1-gnu831
    module load socle-cfd/7.0-gnu850-ompi502
    module load emacs/27.2-gnu831
    export PYTHONEXE=python3
    export OMP_NUM_THREADS=72
    export PRODMODE=1

elif [ "$MAC" = "visung" ]; then
#----------------------------- visung -----------------------------------------
    export ELSAPROD=visung
    export ELSAPROD=$ELSAPROD$EXT
    #. /etc/profile.d/modules-dri.sh
    module purge
    module load occt/7.6.1-gnu831
    module load emacs/27.2-gnu831
    module load socle-cfd/6.0-intel2220-impi
    export PYTHONEXE=python3
    export OMP_NUM_THREADS=72
    export PRODMODE=1
    export I_MPI_FABRICS=shm

elif [ "$MAC" = "cobalt" ]; then
#-------------------------------- cobalt --------------------------------------
    export ELSAPROD=cobalt
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=28
    module purge
    module load intel/17.0.6.256
    module load mpi/openmpi
    module load python/2.7.14
    module load hdf5/1.8.20
    module load libosmesa/10.6.5
    module load libpng/1.6.23

elif [ "$MAC" = "irene" ]; then
#-------------------------------- irene ---------------------------------------
    export ELSAPROD=irene
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=24
    module purge
    module load intel/20
    module load mpi/openmpi
    module load python/2.7.14
    module load hdf5/1.8.20
    #module load scons/3.0.1

elif [ "$MAC" = "jean_zay" ]; then
#-------------------------------- jean-zay ------------------------------------
    export ELSAPROD=jean_zay
    export ELSAPROD=$ELSAPROD$EXT
    module load python/3.8.2
    module load gcc/9.1.0-cuda-openacc
    module load openmpi/4.1.1-cuda
    module load hdf5/1.10.5
    export PYTHONEXE=python3
    # Number of threads
    export OMP_NUM_THREADS=28

elif [ "$MAC" = "spiro" ]; then
#----------------------------- spiro ------------------------------------------
    export ELSAPROD=spiro
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    source /opt/tools/Modules/init/bash
    module purge
    module load socle-cfd/5.0-intel2120-impi
    #module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load emacs/27.2-gnu831
    alias inspxe-cl="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect mi3 -- python3 "
    alias inspxe-cl2="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect ti3 -- python3 "
    alias inspxe-gui="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-gui result"
    alias vtune="vtune -collect hotspots -result-dir result -quiet"
    export PYTHONEXE=python3
    export PRODMODE=1
    unset I_MPI_FABRICS_LIST
    unset I_MPI_FABRICS
    unset I_MPI_TCP_NETMASK
    unset I_MPI_PMI_LIBRARY
    unset $(env | grep SLURM | cut -d'=' -f 1)
    unset OMP_PLACES

elif [ "$MAC" = "juno" ]; then
#----------------------------- juno -------------------------------------------
    export ELSAPROD=juno
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    source /opt/tools/Modules/init/bash
    module purge
    module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load emacs/27.2-gnu831
    module load texlive/2021
    alias inspxe-cl="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect mi3 -- python3 "
    alias inspxe-cl2="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect ti3 -- python3 "
    alias inspxe-gui="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-gui result"
    alias vtune="vtune -collect hotspots -result-dir result -quiet"
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    unset I_MPI_FABRICS_LIST
    unset I_MPI_FABRICS
    unset I_MPI_TCP_NETMASK
    unset I_MPI_PMI_LIBRARY
    unset I_MPI_HYDRA_BOOTSTRAP_EXEC_EXTRA_ARGS I_MPI_HYDRA_BOOTSTRAP HYDRA_BOOTSTRAP
    unset $(env | grep SLURM | cut -d'=' -f 1)
    unset OMP_PLACES

elif [ "$MAC" = "juno_gcc" ]; then
#----------------------------- juno gcc ---------------------------------------
    export ELSAPROD=juno_gcc
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    # modules
    source /opt/tools/Modules/init/bash
    module purge
    #module load gcc/10.2.0
    #module load python/3.10.8-gnu831
    #module load hdf5/1.10.5-gnu831-ompi405
    module load lapack/3.9.1-gnu831
    module load occt/7.6.1-gnu831
    module load socle-cfd/7.0-gnu850-ompi502
    module load emacs/27.2-gnu831
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/opt/tools/gcc/12.1.0-gnu850/lib64/libasan.so
    unset $(env | grep SLURM | cut -d'=' -f 1)
    unset OMP_PLACES

elif [ "$MAC" = "juno_gpu" ]; then
#----------------------------- juno gpu ------------------------------------
    export ELSAPROD=juno_gpu
    export ELSAPROD=$ELSAPROD$EXT
    source /opt/tools/Modules/init/bash
    module purge
    module load python/3.12.2-gnu850
    module load nvhpc/23.7-gnu850-full
    module load hdf5/1.10.5-gnu831-ompi405
    export PYTHONEXE=python3
    # Number of threads
    export OMP_NUM_THREADS=48
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    unset $(env | grep SLURM | cut -d'=' -f 1)
    unset OMP_PLACES

elif [ "$MAC" = "juno_coda" ]; then
#----------------------------- juno coda --------------------------------------
    export ELSAPROD=juno_coda
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    source /opt/tools/Modules/init/bash
    module purge
    module load lapack/3.9.1-gnu831
    module load occt/7.6.1-gnu831
    module load fmt/8.1.1-gnu831 gcc/12.1.0 openmpi/4.0.5-gnu831 python/3.10.8-gnu831 swig/4.2.1-gnu850
    export PATH=/stck/rhea/opt/python3.10_modules/bin:${PATH}
    export PYTHONPATH=/stck/rhea/opt/python3.10_modules/lib/python3.10/site-packages:${PYTHONPATH}
    module use /stck/rhea/juno_coda_v2025_08/modules/linux-rocky8-x86_64_v3
    module load coda/2025.08.0-gnu12.1.0 fszoltanintegration/2025.08.0-gnu12.1.0 fsoversetblanking/2025.08.0-gnu12.1.0 fsui-coda/2025.08.0-gnu12.1.0 fsui-coda-plugin-coda-coupling/2025.08.0-gnu12.1.0 fsgridvelocity/2025.08.0-gnu12.1.0
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/opt/tools/gcc/12.1.0-gnu831/lib64/libasan.so
    unset $(env | grep SLURM | cut -d'=' -f 1)
    unset OMP_PLACES

elif [ "$MAC" = "juno_coda2" ]; then
#----------------------------- juno coda --------------------------------------
    export ELSAPROD=juno_coda
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    #. /etc/profile.d/modules-onera.sh
    export MODULEPATH=/stck/rhea/coda_modules:$MODULEPATH
    CASSIOPEESAVE=$CASSIOPEE
    ELSAPRODSAVE=$ELSAPROD
    module purge
    module load fssuite/2025.02.0-gnu1210
    export CASSIOPEE=$CASSIOPEESAVE
    export ELSAPROD=$ELSAPRODSAVE
    module load lapack/3.9.1-gnu831
    module load occt/7.6.1-gnu831
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    #export OMP_DISPLAY_ENV=VERBOSE
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/opt/tools/gcc/12.1.0-gnu831/lib64/libasan.so
    unset $(env | grep SLURM | cut -d'=' -f 1)
    unset OMP_PLACES

elif [ "$MAC" = "topaze" ]; then
#----------------------------- topaze ccrt proc amd milan ---------------------
    export ELSAPROD=topaze
    export ELSAPROD=$ELSAPROD$EXT
    . /etc/profile.d/module.sh
    module purge
    module load intel/20 mpi/openmpi/4 flavor/hdf5/parallel hdf5/1.8.20
    module load python3/3.8.10
    module load scons/4.4.0
    export LD_PRELOAD=/ccc/products2/icc-20.0.0/Rhel_8__x86_64/system/default/compilers_and_libraries_2020.0.166/linux/compiler/lib/intel64_lin/libiomp5.so
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    # Number of threads
    export OMP_NUM_THREADS=64
    export KMP_AFFINITY=verbose
    export OMP_PLACES=cores

elif [ "$MAC" = "sator_sky" ]; then
#----------------------------- sator skylake ----------------------------------
    export ELSAPROD=sator_sky
    export ELSAPROD=$ELSAPROD$EXT
    . /etc/profile.d/module.sh
    module purge
    #module load socle-cfd/5.0-intel2120-impi
    module load python/3.7.4-intel2120
    module load hdf5/1.10.5-intel2120-impi
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    unset I_MPI_PMI_LIBRARY
    export PYTHONEXE=python3
    # Number of threads
    export OMP_NUM_THREADS=44
    export OMP_PLACES=cores

elif [ "$MAC" = "sator_cas" ]; then
#----------------------------- sator for cascade ------------------------------
    export ELSAPROD=sator_cas
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"
    export OMP_PLACES=cores
    . /etc/profile.d/module.sh
    module purge
    #module load socle-cfd/5.0-intel2120-impi
    module load python/3.7.4-intel2120
    module load hdf5/1.10.5-intel2120-impi
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    unset I_MPI_PMI_LIBRARY
    export PYTHONEXE=python3
    # Other aliases
    alias ffmpeg=/opt/tools/altair/2021.1/altair/hwdesktop/hw/bin/linux64/ffmpeg

elif [ "$MAC" = "sator_sph" ]; then
#----------------------------- sator for saphire ------------------------------
    export ELSAPROD=sator_sph
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    module purge
    module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load emacs/27.2-gnu831
    unset I_MPI_FABRICS_LIST
    unset I_MPI_FABRICS
    unset I_MPI_PMI_LIBRARY
    unset I_MPI_TCP_NETMASK
    export OMP_PLACES=cores
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    
elif [ "$MAC" = "sator_gcc" ]; then
#----------------------------- sator gcc --------------------------------------
    export ELSAPROD=sator_gcc
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    source /opt/tools/Modules/init/bash
    module purge
    module load socle-cfd/7.0-gnu850-ompi502
    module load occt/7.6.1-gnu831
    module load emacs/27.2-gnu831
    export OMP_PLACES=cores
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/opt/tools/gcc/12.1.0-gnu831/lib64/libasan.so

elif [ "$MAC" = "sator_coda" ]; then
#----------------------------- sator coda -------------------------------------
    export ELSAPROD=sator_coda
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    source /opt/tools/Modules/init/bash
    module purge
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    module load fmt/8.1.1-gnu831 gcc/12.1.0 openmpi/4.0.5-gnu831 python/3.10.8-gnu831 swig/4.2.1-gnu850
    export PATH=/stck/rhea/opt/python3.10_modules/bin:${PATH}
    export PYTHONPATH=/stck/rhea/opt/python3.10_modules/lib/python3.10/site-packages:${PYTHONPATH}
    module use /tmp_user/sator/rhea/sator_coda_v2025_08/modules/linux-rocky8-x86_64_v3
    module load coda/2025.08.0-gnu12.1.0 fszoltanintegration/2025.08.0-gnu12.1.0 fsoversetblanking/2025.08.0-gnu12.1.0 fsui-coda/2025.08.0-gnu12.1.0 fsui-coda-plugin-coda-coupling/2025.08.0-gnu12.1.0 fsgridvelocity/2025.08.0-gnu12.1.0
    export OMP_PLACES=cores
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/opt/tools/gcc/12.1.0-gnu831/lib64/libasan.so

elif [ "$MAC" = "sator_coda2" ]; then
#----------------------------- sator coda --------------------------------------
    export ELSAPROD=sator_coda2
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=48
    export MODULEPATH=/tmp_user/sator/rhea/coda_modules:$MODULEPATH
    CASSIOPEESAVE=$CASSIOPEE
    ELSAPRODSAVE=$ELSAPROD
    module purge
    module load emacs
    module load fssuite/2025.02.0-gnu1210
    export CASSIOPEE=$CASSIOPEESAVE
    export ELSAPROD=$ELSAPRODSAVE
    module load occt/7.6.1-gnu831
    export OMP_PLACES=cores
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
    export ASAN_OPTIONS=verify_asan_link_order=false:handle_abort=1
    export LSAN_OPTIONS=suppressions=$CASSIOPEE/Dist/bin/"$ELSAPROD"/asan.supp:print_suppressions=0
    export ASAN_LIB=/opt/tools/gcc/12.1.0-gnu831/lib64/libasan.so

elif [ "$MAC" = "adastra" ]; then
#----------------------------- adastra cpu  -----------------------------------
    export ELSAPROD=adastra
    export ELSAPROD=$ELSAPROD$EXT
    export OMP_NUM_THREADS=48
    export OMP_PLACES=cores
    export PRODMODE=1
    module purge
    # CPU craycc
    #module load craype-x86-genoa
    #module load PrgEnv-cray
    #module load cray-mpich/8.1.28
    #module load cray-libsci/23.05.1.4
    #module load CCE-CPU-3.1.0
    # CPU GCC
    module load PrgEnv-gnu
    export LD_LIBRARY_PATH="/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12":$LD_LIBRARY_PATH
    module load cray-python/3.11.5
    module load cray-hdf5-parallel/1.12.2.5
    export LD_LIBRARY_PATH="$CRAY_LD_LIBRARY_PATH":"$LD_LIBRARY_PATH"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"/opt/cray/pe/python/3.11.5/lib"
    export PYTHONEXE=python3

elif [ "$MAC" = "adastra_gpu" ]; then
#----------------------------- adastra gpu  -----------------------------------
    export ELSAPROD=adastra_gpu
    export ELSAPROD=$ELSAPROD$EXT
    export OMP_NUM_THREADS=12
    export OMP_PLACES=cores
    export PRODMODE=1
    #module purge
    #module load CCE-GPU-3.1.0
    #module load rocm
    #module load cray-python/3.11.5
    #module load cray-hdf5-parallel/1.12.2.5
    module purge
    module load cpe/23.12
    module load craype-accel-amd-gfx90a craype-x86-trento
    module load PrgEnv-cray
    module load rocm
    module load cray-python/3.11.5
    module load cray-hdf5-parallel/1.12.2.5
    #export LD_LIBRARY_PATH="$CRAY_LD_LIBRARY_PATH":"$LD_LIBRARY_PATH"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"/opt/cray/pe/python/3.11.5/lib"
    export PYTHONEXE=python3
    
elif [ "$MAC" = "atlas" ]; then
#----------------------------- Atlas msys2  -----------------------------------
    export ELSAPROD=win64
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=12
    export PYTHONEXE=python3
    export PRODMODE=1

elif [ "$MAC" = "WDAAA161Z" ]; then
#----------------------------- msys64 "AlainRE"  ------------------------------
    export ELSAPROD=win64
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=4
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1

elif [ "$MAC" = "msys2" ]; then
#----------------------------- msys2 (generic)  -------------------------------
    export ELSAPROD=win64
    export ELSAPROD=$ELSAPROD$EXT
    # Nbre de threads
    export OMP_NUM_THREADS=4
    export PYTHONEXE=python3
    export PRODMODE=1
    export PIP_DISABLE_PIP_VERSION_CHECK=1
fi
fi

getSupportedMachines() {
    local script_path="$1"
    grep -E '^\s*(if|elif)\s*\[\s*"\$MAC"\s*=\s*"' "$script_path" \
      | sed -E 's/.*"\$MAC"\s*=\s*"([^"]+)".*/\1/'
}

if [ -z $ELSAPROD ]; then
    echo 'Error: your machine was not found in Envs.'
    # Check names of all listed MACHINEs in this file and in sh_Cassiopee_user
    SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
    MACS_LOCAL=$(getSupportedMachines "$SCRIPT_PATH")
    SCRIPT_PATH="${SCRIPT_PATH:0:-5}user"
    echo 'Supported MACHINE values are:'
    echo "$MACS_LOCAL"
    if [ -e $SCRIPT_PATH ]; then
        MACS_USER=$(getSupportedMachines "$SCRIPT_PATH")
        echo "$MACS_USER"
    fi
    return 1
fi

#-------------------------- Common to all prods -------------------------------
# Chemin de l'executable python
if ! [ -z $PATHL ]; then
    OLD_PATHL=$PATHL
    OLD_LD_LIBRARY_PATHL=$LD_LIBRARY_PATHL
    OLD_PYTHONPATHL=$PYTHONPATHL
fi

if [ "$PYTHONEXE" = "python3" ]; then
    pyversion="python"`python3 -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`
    alias python=python3
else
    pyversion="python"`python -c "import sys; print('.'.join(str(n) for n in sys.version_info[:2]))"`
fi
# Detect if pyenv is used
pyenv=$($PYTHONEXE -c 'import sys; print("pyenv" in sys.executable)' 2>/dev/null)

pylib="lib"
if [ "$MAC" = "ubuntu" ] && [ "$pyenv" == "False" ]; then
    pylib="local/"$pylib
    pysite="dist-packages"
else
    pysite="site-packages"
fi

export PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin
export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/"$pylib"
export PYTHONPATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/"$pylib"/"$pyversion"/"$pysite"

if ! [ -z $OLD_PATHL ]; then
    # Remove all occurences of old paths
    PATH="${PATH//$OLD_PATHL/}"
    LD_LIBRARY_PATH="${LD_LIBRARY_PATH//$OLD_LD_LIBRARY_PATHL/}"
    PYTHONPATH="${PYTHONPATH//$OLD_PYTHONPATHL/}"
    
    # Remove empty paths
    PATH=$(echo "$PATH" | sed 's/::\+/:/g; s/^:\|:$//g')
    LD_LIBRARY_PATH=$(echo "$LD_LIBRARY_PATH" | sed 's/::\+/:/g; s/^:\|:$//g')
    PYTHONPATH=$(echo "$PYTHONPATH" | sed 's/::\+/:/g; s/^:\|:$//g')
fi

# Prefix with new paths
if [ -n "$PATH" ]; then
    export PATH=$PATHL:$PATH
else
    export PATH=$PATHL
fi
if [ -n "$LD_LIBRARY_PATH" ]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATHL:$LD_LIBRARY_PATH
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATHL
fi
if [ -n "$PYTHONPATH" ]; then
    export PYTHONPATH=$PYTHONPATHL:$PYTHONPATH
else
    export PYTHONPATH=$PYTHONPATHL
fi

echo '>> Hello from '$MAC', '$ELSAPROD' production is set.'
