#! /bin/sh
# *Cassiopee* Compilation Environment

#-----------------------------------------------------------------------------
if [ "$CASSIOPEE" = "" ]; then
    echo 'You must specify a CASSIOPEE variable in your environment.'
    echo 'This variable specifies the installation path of *Cassiopee*.'
else
    if test -e $CASSIOPEE/Cassiopee/Envs/sh_Cassiopee_local 
    then
        . $CASSIOPEE/Cassiopee/Envs/sh_Cassiopee_local
    else
        . $CASSIOPEE/Dist/sh_Cassiopee_local
    fi
fi
