import os
import Dist

#==============================================================================
# Write KCore installation path to installPath.py
Dist.writeInstallPath()

prod = os.getenv("ELSAPROD") or 'xx'
SConscript('setup.scons', variant_dir='build/'+prod)