#! /bin/sh
# *Cassiopee* machine specific (local) variables

# Preliminary checks
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

# Environement
ulimit -s unlimited

# Compilation on different machines:
# eos: x86 processors, intel compilers -> x86
# cephee: x86 processors, intel compilers -> cp
# Linux ubuntu: distribution Linux Ubuntu, g++, gfortran -> ub
# stelvio: x86 processors, intel compilers -> stv

# Detection machine (shortest first)
KC=`uname -n`
MAC0=$(echo $KC | grep 'n'); if [ "$MAC0" != "" ]; then export MAC="sator_brw"; fi
MAC0=$(echo $KC | grep 'ld'); if [ "$MAC0" != "" ]; then export MAC="ld"; fi
MAC0=$(echo $KC | grep 'clausius'); if [ "$MAC0" != "" ]; then export MAC="ld"; fi
MAC0=$(echo $KC | grep 'eos'); if [ "$MAC0" != "" ]; then export MAC="eos"; fi
MAC0=$(echo $KC | grep 'ubuntu'); if [ "$MAC0" != "" ]; then export MAC="ubuntu"; fi
MAC0=$(echo $KC | grep 'fulvio'); if [ "$MAC0" != "" ]; then export MAC="fulvio"; fi
MAC0=$(echo $KC | grep 'daapuv'); if [ "$MAC0" != "" ]; then export MAC="daapuv"; fi
MAC0=$(echo $KC | grep 'visio'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'tiamat'); if [ "$MAC0" != "" ]; then export MAC="tiamat"; fi
MAC0=$(echo $KC | grep 'austri'); if [ "$MAC0" != "" ]; then export MAC="austri"; fi
MAC0=$(echo $KC | grep 'laura'); if [ "$MAC0" != "" ]; then export MAC="laura"; fi
MAC0=$(echo $KC | grep 'celeste'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'elmer'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'dumbo'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'ganesh'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'visung'); if [ "$MAC0" != "" ]; then export MAC="visung"; fi
MAC0=$(echo $KC | grep 'moloch'); if [ "$MAC0" != "" ]; then export MAC="moloch"; fi
MAC0=$(echo $KC | grep 'giulia'); if [ "$MAC0" != "" ]; then export MAC="giulia"; fi
MAC0=$(echo $KC | grep 'westri'); if [ "$MAC0" != "" ]; then export MAC="westri"; fi
MAC0=$(echo $KC | grep 'sator'); if [ "$MAC0" != "" ]; then export MAC="sator_brw"; fi
MAC0=$(echo $KC | grep 'jean-zay'); if [ "$MAC0" != "" ]; then export MAC="jean-zay"; fi
MAC0=$(echo $KC | grep 'xdaap'); if [ "$MAC0" != "" ]; then export MAC="xdaap"; fi
MAC0=$(echo $KC | grep 'spiro'); if [ "$MAC0" != "" ]; then export MAC="spiro_el8"; fi
MAC0=$(echo $KC | grep 'cobalt'); if [ "$MAC0" != "" ]; then export MAC="cobalt"; fi
MAC0=$(echo $KC | grep 'irene'); if [ "$MAC0" != "" ]; then export MAC="irene"; fi
MAC0=$(echo $KC | grep 'jean-zay'); if [ "$MAC0" != "" ]; then export MAC="jean-zay"; fi
MAC0=$(echo $KC | grep 'node6.cluster'); if [ "$MAC0" != "" ]; then export MAC="macosx"; fi
MAC0=$(echo $KC | grep 'topaze'); if [ "$MAC0" != "" ]; then export MAC="topaze"; fi

if [ "$MACHINE" != "" ]; then
    export MAC=$MACHINE
fi
#echo 'Cassiopee :: MACHINE NAME::'$MAC, $KC, $MACHINE
echo $MAC0
# ----------------------------- Common ----------------------------------------

if [ "$MAC" = "ld_eos8" ]; then
#------------------------------- ld centos 8 + python 3 -----------------------------------
    export ELSAPROD=eos8_r8
    #module unload $(module -t list 2>&1 | grep -i intel)
    #module purge
    module unload intel/19.0.5
    module unload impi/19.0.5
    #module load oce/7.5.0-gnu831
    module load occt/7.6.1-gnu831
    module load python/3.6.1-gnu831
    #module load python/3.10.8-gnu831
    module load intel/21.2.0
    #module load impi/21.2.0
    module load hdf5/1.8.17-intel2120
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    alias python=python3
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages

elif [ "$MAC" = "ld" ]; then
#------------------------------- ld centos 8 + python 3 -----------------------------------
    export ELSAPROD=ld
    module purge
    module load occt/7.6.1-gnu831
    module load python/3.8.14-gnu831
    #module load intel/21.2.0
    module load gcc/10.2.0
    module load hdf5/1.10.5-gnu831-ompi405
    module load lapack/3.9.1-gnu831
    unset I_MPI_PMI_LIBRARY
    export PRODMODE=1
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    alias python=python3
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.8/site-packages

elif [ "$MAC" = "ld_python2" ]; then
#------------------------------- ld centos 7 -----------------------------------
    export ELSAPROD=x86_r8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load python/2.7.8
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.8
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3],explicit"
    # chemin de mpirun (forced)
    #export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/lib:/stck/benoit/opencascade/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages
    # Pour utilisation MKL+numpy
    #export LD_PRELOAD=/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_avx2.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_def.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_core.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_lp64.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_thread.so:/opt/tools/intel/studio/2017/lib/intel64/libiomp5.so

elif [ "$MAC" = "eos" ]; then
#------------------------------- eos -----------------------------------
    export ELSAPROD=x86_r8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load python/2.7.8
    module load intel/17.0.4
    module unload impi/17
    module load hdf5/1.8.8
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3],explicit"
    # chemin de mpirun (forced)
    export PATH=/usr/lib64/openmpi/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/lib64/openmpi/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages
    # Pour utilisation MKL+numpy
    #export LD_PRELOAD=/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_avx2.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_def.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_core.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_lp64.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_thread.so:/opt/tools/intel/studio/2017/lib/intel64/libiomp5.so

elif [ "$MAC" = "macosx" ]; then
#----------------------------- Mac OSX-----------------------------------------
    export ELSAPROD=macosx_r8
    export OMP_NUM_THREADS=2
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/opt/intel/composer_xe_2015/lib
    unset BUNDLE
    export MACOSX_DEPLOYMENT_TARGET=10.10
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages
    export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATHL

elif [ "$MAC" = "sgi" ]; then
#-------------------------------- SGI -----------------------------------------
    export ELSAPROD=sgi_r8
    export LD_LIBRARY_PATHL=/tools/py/tmp/local/lib/:$CASSIOPEE/Kernel/lib/$ELSAPROD

elif [ "$MAC" = "mangrove" ]; then
#-------------------------------- mangrove -------------------------------------
    export ELSAPROD=man_r8
    export OMP_NUM_THREADS=4
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/opt/intel/Compiler/11.0/0.83/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py::$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.6/site-packages

elif [ "$MAC" = "ubuntu" ]; then
#-------------------------------- ubuntu --------------------------------------
    export ELSAPROD=ub_r8
    export OMP_NUM_THREADS=2
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.5/site-packages

elif [ "$MAC" = "fulvio" ]; then
#----------------------------- fulvio -----------------------------------------
    export ELSAPROD=flv_r8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/4.8.1
    module load intel/15.0.6
    #module load impi/13
    # Nbre de threads
    export OMP_NUM_THREADS=8
    # Chemin de l'executable python
    export PATH=/usr/local/python/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.8/lib:/usr/local/gtk+3/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "daapuv" ]; then
#----------------------------- daapuv -----------------------------------------
    export ELSAPROD=uv_r8
    export OMP_NUM_THREADS=4
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-1.8.7/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.6/site-packages

elif [ "$MAC" = "visio" ]; then
#----------------------------- visio -----------------------------------------
    export ELSAPROD=vis_r8
    . /etc/profile.d/modules-dri.sh
    module load subversion/1.7.6
    module load python/2.7.8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/4.8.1
    module load intel/17.0.4
    module load impi/17
    # Nombre de threads
    export OMP_NUM_THREADS=16
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade2/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.8/lib:/usr/local/gtk+3/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "spiro_gcc" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_gcc
    # Nbre de threads
    export OMP_NUM_THREADS=24
    module purge
    module load occt/7.6.1-gnu831
    #module load python/3.6.1-gnu831
    module load python/3.10.8-gnu831
    module load gcc/10.2.0
    module load hdf5/1.10.5-gnu831-ompi405
    export PYTHONEXE=python3
    alias python=python3
    export PRODMODE=1
    export OMP_PLACES=cores
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.10/site-packages

elif [ "$MAC" = "visung" ]; then
#----------------------------- visung -----------------------------------------
    export ELSAPROD=visung_r8
    . /etc/profile.d/modules-onera.sh
    module purge
    module load subversion
    module load occt/7.6.1-gnu831
    module load python/3.8.14-gnu831
    #module load intel/21.2.0
    module load gcc/10.2.0
    module load hdf5/1.10.5-gnu831-ompi405
    export PRODMODE=1
    export PYTHONEXE=python3
    alias python=python3
    # Nombre de threads
    export OMP_NUM_THREADS=72
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.8/site-packages

elif [ "$MAC" = "visung_el8" ]; then
#----------------------------- visung -----------------------------------------
    export ELSAPROD=visung_el8
    #. /etc/profile.d/modules-dri.sh
    module purge
    module load subversion
    module load python/3.7.4-intel2120
    module load intel/21.2.0
    module load hdf5/1.10.5-intel2120-impi
    module load occt/7.6.1-gnu831
    export PYTHONEXE=python3
    alias python=python3
    export OMP_NUM_THREADS=72
    #export PRODMODE=1
    #export PIP_DISABLE_PIP_VERSION_CHECK=1
    unset I_MPI_PMI_LIBRARY
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.7/site-packages

elif [ "$MAC" = "tiamat" ]; then
#----------------------------- tiamat -----------------------------------------
    export ELSAPROD=tia_r8
    # Nbre de threads
    export OMP_NUM_THREADS=12
    export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11],explicit"
    # modules
    #module unload $(module -t list 2>&1 | grep -i intel)
    #module load python/2.6.4-intel-16.mpt
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel/16.0.4
    # Chemin de l'executable python
    export PATH=/home/tools/local/tiamat/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/home/tools/local/tiamat/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib64:/stck/benoit/x86_64t/lib
    export PYTHONPATHL=/home/tools/local/tiamat/lib/python2.7:$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib64/python2.7/site-packages

elif [ "$MAC" = "austri" ]; then
#----------------------------- austri -----------------------------------------
    export ELSAPROD=aus_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,2,4,6,8,10,12,14,16,18,20,22,1,3,5,7,9,11,13,15,17,19,21,23],explicit"
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11],explicit"
    # modules
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/4.9
    module load intel/17.0.4
    module load impi/17 # very bad install
    module unload impi/17
    module load hdf5/1.8.8-intel-11
    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/aus/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "laura" ]; then
#----------------------------- laura ------------------------------------------
    export ELSAPROD=laura_r8
    # Chargement des modules
    #. /usr/share/modules/init/bash
    module load python/2.7.3.icc-mpt
    module load hdf5/1.8.7
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel-mkl-10/10.3.1
    module load intel-cce-12/12.0.1.107
    module load intel-fce-12/12.0.1.107
    module load mpt/2.02
    export OMP_NUM_THREADS=12
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/stck/benoit/laura/lib:/usr/local/lib64:/opt/intel/composerxe-2011.1.107/compiler/lib/intel64
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "moloch" ]; then
#----------------------------- moloch -----------------------------------------
    export ELSAPROD=mol_r8
    # Nbre de threads
    export OMP_NUM_THREADS=12
    # modules
    module load python/2.6.4/11.mpt
    module load hdf5/1.8.8-intel-11
    # Chemin de l'executable python
    export PATH=/usr/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib64/python2.6/site-packages

elif [ "$MAC" = "giulia" ]; then
#----------------------------- giulia -----------------------------------------
    export ELSAPROD=giu_r8
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    # modules
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/5.2
    module load python/2.7.8
    module load intel/17.0.4
    module load impi/16
    module unload hdf5/1.8.8
    module load hdf5/1.8.8-intel-16.impi
    #module purge
    #module load   python/2.7.8
    #source /stck/nalferez/intel/parallel_studio_xe_2018/psxevars.sh
    #export PATH=/stck5/nalferez/intel/2018update2/PythonIntel/intelpython2/bin/:/usr/local/python-gnu-2.7.8/bin/:$PATH

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib64:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "westri" ]; then
#----------------------------- westri (KNL) -----------------------------------------
    export ELSAPROD=wes_r8
    # Nbre de threads
    export OMP_NUM_THREADS=64
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11],explicit"
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63],explicit"
    export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63],explicit"
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,64,128,1921,65,129,1932,66,130,1943,67,131,1954,68,132,1965,69,133,1976,70,134,1987,71,135,1998,72,136,2009,73,137,20110,74,138,20211,75,139,20312,76,140,20413,77,141,20514,78,142,20615,79,143,20716,80,144,20817,81,145,20918,82,146,21019,83,147,21120,84,148,21221,85,149,21322,86,150,21423,87,151,21524,88,152,21625,89,153,21726,90,154,21827,91,155,21928,92,156,22029,93,157,22130,94,158,22231,95,159,22332,96,160,22433,97,161,22534,98,162,22635,99,163,22736,100,164,22837,101,165,22938,102,166,23039,103,167,23140,104,168,23241,105,169,23342,106,170,23443,107,171,23544,108,172,23645,109,173,23746,110,174,23847,111,175,23948,112,176,24049,113,177,24150,114,178,24251,115,179,24352,116,180,24453,117,181,24554,118,182,24655,119,183,24756,120,184,24857,121,185,24958,122,186,25059,123,187,25160,124,188,25261,125,189,25362,126,190,25463,127,191,255],explicit"
    export PROC_NAME="KNL"
    # modules
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel/17.0.4
    module load hdf5/1.8.8-intel-16
    module load python/2.7.8

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/aus/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "cobalt" ]; then
#-------------------------------- cobalt -----------------------------------------
    export ELSAPROD=cob_r8
    # Nbre de threads
    export OMP_NUM_THREADS=28

    # modules
    module purge
    module load intel/17.0.6.256
    module load mpi/openmpi
    module load python/2.7.14
    module load hdf5/1.8.20
    module load libosmesa/10.6.5
    module load libpng/1.6.23

    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "tgcc_irene" ]; then
#-------------------------------- irene -----------------------------------------
    export ELSAPROD=irene_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    echo 'TGCC_IRENE SH_CASSIOPEE_LOCAL _v2'
    # modules
    module purge
    module load intel/20
    module load mpi/openmpi
    module load python/2.7.14
    module load hdf5/1.8.20
    #module load scons/3.0.1

    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "jean-zay" ]; then
#-------------------------------- jean-zay -----------------------------------------
    export ELSAPROD=jz_r8
    module load python/3.8.2
    module load gcc/9.1.0-cuda-openacc
    module load openmpi/4.1.1-cuda
    module load hdf5/1.10.5
    # Set next two lines only if python is not python
    export PYTHONEXE=python3    
    alias python=python3
    # Number of threads
    export OMP_NUM_THREADS=28
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.8/site-packages

elif [ "$MAC" = "xdaap" ]; then
#----------------------------- xdaap -----------------------------------------
    export ELSAPROD=xdaap_r8
    . /etc/profile.d/modules-dri.sh
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/5.2
    module load intel/15.0.6
    # Nombre de threads
    export OMP_NUM_THREADS=16
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],explicit"
    # Chemin de l'executable python
    export PATH=/usr/local/python/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib64/:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.8/lib:/usr/local/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "spiro" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    #module load CFD/4.0-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8
    module load subversion/1.14.1-gnu830
    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.17/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages

elif [ "$MAC" = "spiro_sky" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_sky_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    #module load CFD/4.0-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8
    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.17/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages

elif [ "$MAC" = "spiro_cas" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_cas_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    #module load CFD/4.0-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8
    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.17/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages

elif [ "$MAC" = "spiro_amdRM" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_amdrm_r8
    # Nbre de threads
    export OMP_NUM_THREADS=32
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)

    module unload impi/17
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8

    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.17/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages

elif [ "$MAC" = "spiro_amdNP" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_amdnp_r8
    # Nbre de threads
    export OMP_NUM_THREADS=32
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)

    module unload impi/17
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    module load python/3.6.1
    module unload hdf5/1.8.8

    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.17/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages

elif [ "$MAC" = "spiro_socle6" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_socle_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    #. /usr/local/Modules/init/bash
    module purge
    module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load subversion/1.14.1-gnu831    
    export PYTHONEXE=python3
    alias python=python3
    export PRODMODE=1
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.8/site-packages

elif [ "$MAC" = "spiro_sonics" ]; then
#----------------------------- spiro sonics -----------------------------------------
    export ELSAPROD=linux64
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /etc/profile.d/modules-onera.sh
    module purge
    source /scratchm/sonics/dist/spiro-el8.sh --compiler=intel@2022 --mpi=impi
    module load emacs
    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade/lib:/stck/benoit/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/opt/tools/hdf5-1.10.5-intel-19-impi-19/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.9/site-packages


elif [ "$MAC" = "spiro_python2" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    #module load CFD/4.0-intel-17.impi
    module load python/2.7.8-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.17-intel-17
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":/lib/usr/local/hdf5-intel-1.8.17/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" = "spiro_anaconda" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_acda
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module unload $(module -t list 2>&1 | grep -i intel)
    module unload impi/17
    #module load CFD/4.0-intel-17.impi
    module load intel/17.0.4
    module load impi/17
    module unload hdf5/1.8.8
    module load hdf5/1.8.17-intel-17
    module load anaconda/2021.05
    module load subversion/1.14.1-gnu830
    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/stck/benoit/opencascade/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/usr/local/hdf5-intel-1.8.17/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.8/site-packages

elif [ "$MAC" = "spiro_el8" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_el8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    #. /usr/local/Modules/init/bash
    module purge
    module load socle-cfd/5.0-intel2120-impi
    #module load socle-cfd/6.0-intel2220-impi
    module load occt/7.6.1-gnu831
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    alias inspxe-cl="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect mi3 -- python3 "
    alias inspxe-cl2="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-cl -r result -collect ti3 -- python3 "
    alias inspxe-gui="/opt/tools/intel/oneapi/inspector/2021.2.0/bin64/inspxe-gui result"
    alias vtune="vtune -collect hotspots -result-dir result -quiet" 
    export PYTHONEXE=python3
    alias python=python3
    export PRODMODE=0
    unset I_MPI_FABRICS_LIST
    unset I_MPI_FABRICS
    unset I_MPI_TCP_NETMASK
    unset I_MPI_PMI_LIBRARY
    unset SLURM_CPU_BIND
    unset SLURM_CPU_BIND_TYPE
    export OMP_PLACES=cores
        
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.7/site-packages

elif [ "$MAC" = "spiro_intel" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_intel
    echo $ELSAPROD
    # Nbre de threads
    export OMP_NUM_THREADS=24
    module purge
    module load intel/19.0.5
    module load occt/7.6.1-gnu831
    module load python/3.6.1-gnu831
    module load hdf5/1.10.3-intel1905
    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages

elif [ "$MAC" = "spiro_coda" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_coda
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    . /usr/local/Modules/init/bash
    module purge
    source /scratchm/rhea/opt/env_dev_coda_spliss_2022_01.sh
    module load subversion/1.14.1-gnu830
    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.9/site-packages

elif [ "$MAC" = "spiro_coda_el8" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_coda_el8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    # modules
    #. /usr/local/Modules/init/bash
    module purge
    source /stck/rhea/opt_el8/dev_coda_spliss_gcc_openmpi_el8.sh
    module load subversion/1.14.1-gnu831
    export PYTHONEXE=python3
    alias python=python3
    export OMP_PLACES=cores
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.9/site-packages

elif [ "$MAC" = "spiro_arm" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_arm
    # Nbre de threads
    export OMP_NUM_THREADS=56
    export PYTHONEXE=python3
    alias python=python3
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib64:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=/usr/lib64/python3.6:$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages:/usr/bin

elif [ "$MAC" = "spiro_pgi" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_pgi
    # Nbre de threads
    export OMP_NUM_THREADS=24
    export PYTHONEXE=python3
    alias python=python3
    module purge
    module load python/3.6.1-gnu831
    module load nvhpc/22.2-gnu831-full
    module load subversion/1.14.1-gnu831
    # Chemin de l'executable python
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.6/site-packages


elif [ "$MAC" = "sator_brw" ]; then
#----------------------------- sator for broadwell -----------------------------------------
    echo 'SATOR - BROADWELL PARTITION'
    export ELSAPROD=sat_r8

    echo "Pour compiler sur skylake, export MACHINE=sator_sky, puis sourcer sh_Cassiopee_r8" 

    . /etc/profile.d/module.sh
    module purge
    module load python/3.7.4-intel2120
    module load hdf5/1.10.5-intel2120-impi
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    alias python=python3
    # Other aliases
    alias ffmpeg=/opt/tools/altair/2021.1/altair/hwdesktop/hw/bin/linux64/ffmpeg    
    # Number of threads

    # Nbre de threads
    export OMP_NUM_THREADS=28
    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"
#    export KMP_AFFINITY="scatter,1,0,granularity=fine,verbose"

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.7/site-packages

elif [ "$MAC" = "topaze" ]; then
#----------------------------- topaze ccrt proc amd milan ---------------------------------------
    echo 'topaze - Milan PARTITION'
    export ELSAPROD=topaze_r8
    . /etc/profile.d/module.sh
    module purge
    module load intel/20 mpi/openmpi/4 flavor/hdf5/parallel hdf5/1.8.20
    module load python3/3.8.10
    module load scons/4.4.0
    export LD_PRELOAD=/ccc/products2/icc-20.0.0/Rhel_8__x86_64/system/default/compilers_and_libraries_2020.0.166/linux/compiler/lib/intel64_lin/libiomp5.so
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    alias python=python3
    # Number of threads
    export OMP_NUM_THREADS=64
    export KMP_AFFINITY=verbose
    export OMP_PLACES=cores
    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.8/site-packages


elif [ "$MAC" = "sator_sky" ]; then
#----------------------------- sator skylake ---------------------------------------
    echo 'SATOR - SKYLAKE PARTITION'
    export ELSAPROD=sat_sky_r8
    . /etc/profile.d/module.sh
    module purge
    #module load socle-cfd/5.0-intel2120-impi
    module load python/3.7.4-intel2120
    module load hdf5/1.10.5-intel2120-impi
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    unset I_MPI_PMI_LIBRARY
    # Set next two lines only if python is not python
    export PYTHONEXE=python3
    alias python=python3
    # Number of threads
    export OMP_NUM_THREADS=44
    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.7/site-packages

elif [ "$MAC" = "sator_cas" ]; then
    #----------------------------- sator for cascade ---------------------------------------
    echo 'SATOR - CASCADE PARTITION'
    export ELSAPROD=sat_cas_r8
    # Nbre de threads
    export OMP_NUM_THREADS=48
    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"

    . /etc/profile.d/module.sh
    module purge
    #module load socle-cfd/5.0-intel2120-impi
    module load python/3.7.4-intel2120
    module load hdf5/1.10.5-intel2120-impi
    module load subversion/1.14.1-gnu831
    module load emacs/27.2-gnu831
    module load occt/7.6.1-gnu831
    unset I_MPI_PMI_LIBRARY
    export PYTHONEXE=python3
    alias python=python3
    # Other aliases
    alias ffmpeg=/opt/tools/altair/2021.1/altair/hwdesktop/hw/bin/linux64/ffmpeg    
    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.7/site-packages

elif [ "$MAC" = "jean-zay" ]; then
#-----------------------------jean-zay IDRIS  ---------------------------------------
    export ELSAPROD=jz_r8
    # Nbre de threads
    export OMP_NUM_THREADS=40
    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"

    # modules 
    #. /etc/profile.d/module.sh
    module load intel-compilers/19.1.3
    module load intel-mpi/2019.9
    module load python/3.7.10
    module load hdf5/1.12.0
    export PYTHONEXE=python3
    alias python=python3
    
    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python3.7/site-packages
fi
#---------------------------Common---------------------------------------------
alias emake='make -f Makefile.$ELSAPROD'

STE=$LD_LIBRARY_PATHL
STES='*'$STE'*'
if [ "$LD_LIBRARY_PATH" = "" ]; then
    export LD_LIBRARY_PATH=$STE
else
    case $LD_LIBRARY_PATH in
	$STES)
#        echo '->var detected; not added'
        ;;
	*)
#        echo $LD_LIBRARY_PATH, $STE
            export LD_LIBRARY_PATH="$STE":"$LD_LIBRARY_PATH"
            ;;
    esac
fi
#echo $LD_LIBRARY_PATH

STE=$PYTHONPATHL
STES='*'$STE'*'
if [ "$PYTHONPATH" = "" ]; then
    export PYTHONPATH=$STE
else
    case $PYTHONPATH in
	$STES)
#        echo '->var detected; not added'
        ;;
	*)
#        echo $PYTHONPATH, $STE
            export PYTHONPATH="$STE":"$PYTHONPATH"
            ;;
    esac
fi
#echo $ELSAPROD' environment set.'
