#! /bin/sh
# *Cassiopee* machine specific (local) variables

# Preliminary checks
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

# Environement
ulimit -s unlimited

# Compilation on different machines:
# eos: x86 processors, intel compilers -> x86
# cephee: x86 processors, intel compilers -> cp
# Linux ubuntu: distribution Linux Ubuntu, g++, gfortran -> ub
# stelvio: x86 processors, intel compilers -> stv

# Detection machine (shortest first)
KC=`uname -n`
MAC0=$(echo $KC | grep 'n'); if [ "$MAC0" != "" ]; then export MAC="sator"; fi
MAC0=$(echo $KC | grep 'ld'); if [ "$MAC0" != "" ]; then export MAC="ld"; fi
MAC0=$(echo $KC | grep 'eos'); if [ "$MAC0" != "" ]; then export MAC="eos"; fi
MAC0=$(echo $KC | grep 'ubuntu'); if [ "$MAC0" != "" ]; then export MAC="ubuntu"; fi
MAC0=$(echo $KC | grep 'fulvio'); if [ "$MAC0" != "" ]; then export MAC="fulvio"; fi
MAC0=$(echo $KC | grep 'daapuv'); if [ "$MAC0" != "" ]; then export MAC="daapuv"; fi
MAC0=$(echo $KC | grep 'visio'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'tiamat'); if [ "$MAC0" != "" ]; then export MAC="tiamat"; fi
MAC0=$(echo $KC | grep 'austri'); if [ "$MAC0" != "" ]; then export MAC="austri"; fi
MAC0=$(echo $KC | grep 'laura'); if [ "$MAC0" != "" ]; then export MAC="laura"; fi
MAC0=$(echo $KC | grep 'celeste'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'elmer'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'dumbo'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'ganesh'); if [ "$MAC0" != "" ]; then export MAC="visio"; fi
MAC0=$(echo $KC | grep 'moloch'); if [ "$MAC0" != "" ]; then export MAC="moloch"; fi
MAC0=$(echo $KC | grep 'giulia'); if [ "$MAC0" != "" ]; then export MAC="giulia"; fi
MAC0=$(echo $KC | grep 'westri'); if [ "$MAC0" != "" ]; then export MAC="westri"; fi
MAC0=$(echo $KC | grep 'sator'); if [ "$MAC0" != "" ]; then export MAC="sator"; fi
MAC0=$(echo $KC | grep 'xdaap'); if [ "$MAC0" != "" ]; then export MAC="xdaap"; fi
MAC0=$(echo $KC | grep 'spiro'); if [ "$MAC0" != "" ]; then export MAC="spiro"; fi
MAC0=$(echo $KC | grep 'cobalt'); if [ "$MAC0" != "" ]; then export MAC="cobalt"; fi
MAC0=$(echo $KC | grep 'ldmfn423z'); if [ "$MAC0" != "" ]; then export MAC="ld"; fi
MAC0=$(echo $KC | grep 'node6.cluster'); if [ "$MAC0" != "" ]; then export MAC="macosx"; fi

# force: sator_sky, ld_pgi
if [ "$MACHINE" != "" ]; then
    export MAC=$MACHINE
fi

# ----------------------------- Common ----------------------------------------
#export ELSADIST=$CASSIOPEE  # production (cfg)
#export ELSAPATH=$CASSIOPEE  # production (cfg)
#export ELSAWKSP=$CASSIOPEE  # production (cfg)

if [ "$MAC" == "ld" ]; then
#------------------------------- ld centos 7 -----------------------------------
    export ELSAPROD=x86_r8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load python/2.7.8
    module load intel/17.0.4
    module load impi/17
    module load hdf5/1.8.8
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3],explicit"
    # chemin de mpirun (forced)
    #export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib64:/home/benoit/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/x86_r8/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/x86_r8:$CASSIOPEE/Dist/bin/x86_r8/lib/python2.7/site-packages
    # Pour utilisation MKL+numpy
    #export LD_PRELOAD=/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_avx2.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_def.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_core.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_lp64.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_thread.so:/opt/tools/intel/studio/2017/lib/intel64/libiomp5.so

elif [ "$MAC" == "eos" ]; then
#------------------------------- eos -----------------------------------
    export ELSAPROD=x86_r8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load python/2.7.8
    module load intel/17.0.4
    module unload impi/17
    module load hdf5/1.8.8
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3],explicit"
    # chemin de mpirun (forced)
    export PATH=/usr/lib64/openmpi/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib64:/stck/benoit/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/x86_r8/lib:/usr/lib64/openmpi/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/x86_r8:$CASSIOPEE/Dist/bin/x86_r8/lib/python2.7/site-packages
    # Pour utilisation MKL+numpy
    #export LD_PRELOAD=/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_avx2.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_def.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_core.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_lp64.so:/opt/tools/intel/studio/2017/mkl/lib/intel64/libmkl_intel_thread.so:/opt/tools/intel/studio/2017/lib/intel64/libiomp5.so

elif [ "$MAC" == "macosx" ]; then
#----------------------------- Mac OSX-----------------------------------------
    export ELSAPROD=macosx_r8
    export OMP_NUM_THREADS=2
    export PATH=$CASSIOPEE/Dist/bin/macosx_r8:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib:/opt/intel/composer_xe_2015/lib
    unset BUNDLE
    export MACOSX_DEPLOYMENT_TARGET=10.10
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages
    export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATHL

elif [ "$MAC" == "sgi" ]; then
#-------------------------------- SGI -----------------------------------------
    export ELSAPROD=sgi_r8
    export LD_LIBRARY_PATHL=/tools/py/tmp/local/lib/:$CASSIOPEE/Kernel/lib/$ELSAPROD

elif [ "$MAC" == "mangrove" ]; then
#-------------------------------- mangrove -------------------------------------
    export ELSAPROD=man_r8
    export OMP_NUM_THREADS=4
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/opt/intel/Compiler/11.0/0.83/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/man_r8/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py::$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/man_r8:$CASSIOPEE/Dist/bin/man_r8/lib/python2.6/site-packages

elif [ "$MAC" == "ubuntu" ]; then
#-------------------------------- ubuntu --------------------------------------
    export ELSAPROD=ub_r8
    export OMP_NUM_THREADS=2
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/ub_r8/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/ub_r8:$CASSIOPEE/Dist/bin/ub_r8/lib/python2.5/site-packages

elif [ "$MAC" == "fulvio" ]; then
#----------------------------- fulvio -----------------------------------------
    export ELSAPROD=flv_r8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel/15.0.6
    #module load   impi/13
    # Nbre de threads
    export OMP_NUM_THREADS=8
    # Chemin de l'executable python
    export PATH=/usr/local/python/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/flv_r8/lib:/usr/local/lib64:/usr/local/hdf5-intel-1.8.8/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/flv_r8:$CASSIOPEE/Dist/bin/flv_r8/lib/python2.7/site-packages

elif [ "$MAC" == "daapuv" ]; then
#----------------------------- daapuv -----------------------------------------
    export ELSAPROD=uv_r8
    export OMP_NUM_THREADS=4
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/uv_r8/lib:/usr/local/hdf5-1.8.7/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/uv_r8:$CASSIOPEE/Dist/bin/uv_r8/lib/python2.6/site-packages

elif [ "$MAC" == "visio" ]; then
#----------------------------- visio -----------------------------------------
    export ELSAPROD=vis_r8
    . /etc/profile.d/modules-dri.sh
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel/15.0.6
    #module load  impi/15
    # Nombre de threads
    export OMP_NUM_THREADS=16
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],explicit"
    # Chemin de l'executable python
    export PATH=/usr/local/python/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/vis_r8/lib:/usr/local/hdf5-intel-1.8.8/lib:/usr/local/lib64:/usr/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/vis_r8:$CASSIOPEE/Dist/bin/vis_r8/lib/python2.7/site-packages

elif [ "$MAC" == "tiamat" ]; then
#----------------------------- tiamat -----------------------------------------
    export ELSAPROD=tia_r8
    # Nbre de threads
    export OMP_NUM_THREADS=12
    export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11],explicit"
    # modules 
    #module unload $(module -t list 2>&1 | grep -i intel)
    #module load python/2.6.4-intel-16.mpt
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel/16.0.4
    # Chemin de l'executable python
    export PATH=/home/tools/local/tiamat/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/home/tools/local/tiamat/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/tia_r8/lib64:/home/benoit/x86_64t/lib
    export PYTHONPATHL=/home/tools/local/tiamat/lib/python2.7:$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/tia_r8:$CASSIOPEE/Dist/bin/tia_r8/lib64/python2.7/site-packages

elif [ "$MAC" == "austri" ]; then
#----------------------------- austri -----------------------------------------
    export ELSAPROD=aus_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24
    export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,2,4,6,8,10,12,14,16,18,20,22,1,3,5,7,9,11,13,15,17,19,21,23],explicit"
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11],explicit"
    # modules 
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel/17.0.4
    module load impi/17 # very bad install
    module unload impi/17
    #module load gcc/5.2
    module load hdf5/1.8.8-intel-11
    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/home/benoit/aus/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/aus_r8/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/aus_r8:$CASSIOPEE/Dist/bin/aus_r8/lib/python2.7/site-packages

elif [ "$MAC" == "laura" ]; then
#----------------------------- laura ------------------------------------------
    export ELSAPROD=laura_r8
    # Chargement des modules
    #. /usr/share/modules/init/bash 
    module load python/2.7.3.icc-mpt
    module load hdf5/1.8.7
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel-mkl-10/10.3.1
    module load intel-cce-12/12.0.1.107
    module load intel-fce-12/12.0.1.107
    module load mpt/2.02
    export OMP_NUM_THREADS=12
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/laura_r8/lib:/home/benoit/laura/lib:/usr/local/lib64:/opt/intel/composerxe-2011.1.107/compiler/lib/intel64
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/laura_r8:$CASSIOPEE/Dist/bin/laura_r8/lib/python2.7/site-packages

elif [ "$MAC" == "moloch" ]; then
#----------------------------- moloch -----------------------------------------
    export ELSAPROD=mol_r8
    # Nbre de threads
    export OMP_NUM_THREADS=12
    # modules 
    module load python/2.6.4/11.mpt
    module load hdf5/1.8.8-intel-11
    # Chemin de l'executable python
    export PATH=/usr/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/mol_r8/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/mol_r8:$CASSIOPEE/Dist/bin/mol_r8/lib64/python2.6/site-packages

elif [ "$MAC" == "giulia" ]; then
#----------------------------- giulia -----------------------------------------
    export ELSAPROD=giu_r8
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    # modules 
    module unload $(module -t list 2>&1 | grep -i intel)
    module load gcc/5.2
    module load python/2.7.8
    module load intel/17.0.4
    module load impi/16
    module unload hdf5/1.8.8
    module load hdf5/1.8.8-intel-16.impi
    #module purge
    #module load   python/2.7.8
    #source /stck/nalferez/intel/parallel_studio_xe_2018/psxevars.sh
    #export PATH=/stck5/nalferez/intel/2018update2/PythonIntel/intelpython2/bin/:/usr/local/python-gnu-2.7.8/bin/:$PATH

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib64:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/giu_r8/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/giu_r8:$CASSIOPEE/Dist/bin/giu_r8/lib/python2.7/site-packages
    # LD_PRELOAD libirc for Intel Python
    #export LD_PRELOAD=/stck5/nalferez/intel/2018update2/PythonIntel/intelpython2/lib/libirc.so:$LD_PRELOAD

elif [ "$MAC" == "westri" ]; then
#----------------------------- westri (KNL) -----------------------------------------
    export ELSAPROD=wes_r8
    # Nbre de threads
    export OMP_NUM_THREADS=64
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11],explicit"
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63],explicit"
    export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63],explicit"                          
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,64,128,1921,65,129,1932,66,130,1943,67,131,1954,68,132,1965,69,133,1976,70,134,1987,71,135,1998,72,136,2009,73,137,20110,74,138,20211,75,139,20312,76,140,20413,77,141,20514,78,142,20615,79,143,20716,80,144,20817,81,145,20918,82,146,21019,83,147,21120,84,148,21221,85,149,21322,86,150,21423,87,151,21524,88,152,21625,89,153,21726,90,154,21827,91,155,21928,92,156,22029,93,157,22130,94,158,22231,95,159,22332,96,160,22433,97,161,22534,98,162,22635,99,163,22736,100,164,22837,101,165,22938,102,166,23039,103,167,23140,104,168,23241,105,169,23342,106,170,23443,107,171,23544,108,172,23645,109,173,23746,110,174,23847,111,175,23948,112,176,24049,113,177,24150,114,178,24251,115,179,24352,116,180,24453,117,181,24554,118,182,24655,119,183,24756,120,184,24857,121,185,24958,122,186,25059,123,187,25160,124,188,25261,125,189,25362,126,190,25463,127,191,255],explicit"                          
    export PROC_NAME="KNL"
    # modules 
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel/17.0.4
    module load hdf5/1.8.8-intel-16
    module load python/2.7.8

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/home/benoit/aus/lib:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/wes_r8/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/wes_r8:$CASSIOPEE/Dist/bin/wes_r8/lib/python2.7/site-packages

elif [ "$MAC" == "cobalt" ]; then 
#-------------------------------- cobalt -----------------------------------------
    export ELSAPROD=cob_r8
    # Nbre de threads
    export OMP_NUM_THREADS=28
    export OMP_PROC_BIND=False
    export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27],explicit"
    export PROC_NAME="BDW"

    # modules 
    module purge
    module load intel/17.0.4.196 mpi/intelmpi/2017.0.4.196 python/2.7.14 hdf5/1.8.16

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/cob_r8/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/cob_r8:$CASSIOPEE/Dist/bin/cob_r8/lib/python2.7/site-packages   

elif [ "$MAC" == "ld" ]; then 
#-------------------------------- ld -----------------------------------------
    export ELSAPROD=x86_r8
    module unload $(module -t list 2>&1 | grep -i intel)
    module load intel/13.1.3
    module load impi/13
    module load hdf5/1.8.8
    # Nbre de threads
    ncpu=$(grep processor /proc/cpuinfo |tail -1 |cut -f2 -d: )
    ncpu=$((ncpu + 1 ))
    export OMP_NUM_THREADS=$ncpu
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3],explicit"
    # Chemin de python
    export PATH=/usr/local/python/bin:$PATH
    # chemin de mpirun (forced)
    export PATH=/usr/lib64/openmpi/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/home/benoit/lib:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/x86_r8/lib:/usr/local/python/lib:/usr/lib64/openmpi/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/x86_r8:$CASSIOPEE/Dist/bin/x86_r8/lib/python2.7/site-packages

elif [ "$MAC" == "xdaap" ] ; then
#----------------------------- xdaap -----------------------------------------
    export ELSAPROD=xdaap_r8
    . /etc/profile.d/modules-dri.sh
    module unload $(module -t list 2>&1 | grep -i intel)
    #module load gcc/4.8.1
    module load intel/15.0.6
    # Nombre de threads
    export OMP_NUM_THREADS=16
    #export KMP_AFFINITY="verbose,granularity=fine,proclist=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],explicit"
    # Chemin de l'executable python
    export PATH=/usr/local/python/bin:$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=/usr/lib64/:$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/xdaap_r8/lib:/usr/local/hdf5-intel-1.8.8/lib:/usr/local/lib64
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/xdaap_r8:$CASSIOPEE/Dist/bin/xdaap_r8/lib/python2.7/site-packages

elif [ "$MAC" == "spiro" ]; then
#----------------------------- spiro -----------------------------------------
    export ELSAPROD=spiro_r8
    # Nbre de threads
    export OMP_NUM_THREADS=24

    # modules 
    module unload $(module -t list 2>&1 | grep -i intel)
    module load CFD/4.0-intel-17.impi

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/spiro_r8/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/sat_r8:$CASSIOPEE/Dist/bin/spiro_r8/lib/python2.7/site-packages

elif [ "$MAC" == "sator" ]; then
#----------------------------- sator -----------------------------------------
    export ELSAPROD=sat_r8
    echo "ELSAPROD=" $ELSAPROD
    echo "pour compiler sur skylake, export MACHINE=sator_sky, puis sourcer sh_Cassiopee_r8" 

    # Nbre de threads
    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"
#    export KMP_AFFINITY="scatter,1,0,granularity=fine,verbose"
    export OMP_NUM_THREADS=28

    # modules 
    module unload $(module -t list 2>&1 | grep -i intel)
    module load CFD/4.0-intel-17.impi
    #module load intel/17.0.4 impi/17 python/2.7.8-intel-17.impi
    #module load gcc/5.2 intel/17.0.4 impi/17 python/2.7.8-intel-17.impi
    #module load gcc/5.2 intel/17.0.4 impi/17 python/2.7.13-intel-17
    # HDF para (deja dans le socle)
    #module load hdf5/1.8.17-intel-17.impi

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

elif [ "$MAC" == "sator_sky" ]; then
#----------------------------- sator skylake ---------------------------------------
    export ELSAPROD=sat_sky_r8
    echo "elsaProd=" $ELSAPROD
    # Nbre de threads
    export OMP_NUM_THREADS=28

    export KMP_AFFINITY="compact,1,0,granularity=fine,verbose"
    export PROC_NAME="SKL"

    # modules 
    module unload $(module -t list 2>&1 | grep -i intel)
    module load CFD/4.0-intel-17.impi
    #module load intel/17.0.4 impi/17 python/2.7.8-intel-17.impi
    #module load gcc/5.2 intel/17.0.4 impi/17 python/2.7.8-intel-17.impi
    #module load gcc/5.2 intel/17.0.4 impi/17 python/2.7.13-intel-17
    # HDF para (deja dans le socle)
    #module load hdf5/1.8.17-intel-17.impi

    # Chemin de l'executable python
    export PATH=$PATH
    export PATH=$PATH:$CASSIOPEE/Dist/bin
    export PATH=$CASSIOPEE/Dist/bin/$ELSAPROD:$CASSIOPEE/Dist/bin/$ELSAPROD/bin:$PATH
    export LD_LIBRARY_PATHL=$CASSIOPEE/Kernel/lib/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib
    export PYTHONPATHL=$CASSIOPEE/Dist/lib/py:$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD":$CASSIOPEE/Dist/bin/"$ELSAPROD"/lib/python2.7/site-packages

fi

#---------------------------Common---------------------------------------------
alias emake='make -f Makefile.$ELSAPROD'

STE=$LD_LIBRARY_PATHL
STES='*'$STE'*'
if [ "$LD_LIBRARY_PATH" = "" ]; then
    export LD_LIBRARY_PATH=$STE
else
    case $LD_LIBRARY_PATH in
	$STES)
#        echo '->var detected; not added'
        ;;
	*)
#        echo $LD_LIBRARY_PATH, $STE 
            export LD_LIBRARY_PATH="$STE":"$LD_LIBRARY_PATH"
            ;;
    esac
fi
#echo $LD_LIBRARY_PATH

STE=$PYTHONPATHL
STES='*'$STE'*'
if [ "$PYTHONPATH" = "" ]; then
    export PYTHONPATH=$STE
else
    case $PYTHONPATH in 
	$STES)
#        echo '->var detected; not added'
        ;;
	*)
#        echo $PYTHONPATH, $STE 
            export PYTHONPATH="$STE":"$PYTHONPATH"
            ;;
    esac
fi
#echo $PYTHONPATH
#echo $ELSAPROD' environment set.'
