#! /bin/sh
# *Cassiopee* Shadow Environment

#---------------------------- User Data --------------------------------------
# Using MPI?
export MPI=false
# Using debug mode?
export DBG=false
#-----------------------------------------------------------------------------

export CASSIOPEE_ORIG=$CASSIOPEE
export CASSIOPEE=/home/cwervaec/Cassiopee

if test -e $CASSIOPEE/Apps/Modules/Envs/sh_Cassiopee_local 
then
    . $CASSIOPEE/Apps/Modules/Envs/sh_Cassiopee_local
else
    . $CASSIOPEE/Dist/sh_Cassiopee_local
fi

export CASSIOPEE=$CASSIOPEE_ORIG
if test -e $CASSIOPEE/Apps/Modules/Envs/sh_Cassiopee_local 
then
    . $CASSIOPEE/Apps/Modules/Envs/sh_Cassiopee_local
else
    . $CASSIOPEE/Dist/sh_Cassiopee_local
fi