#! /bin/sh
if [ "$PYTHONEXE" != "" ]; then
    alias python=$PYTHONEXE
fi
if test -e "$CASSIOPEE/Dist/bin/$ELSAPROD/notifyValid.py"
then
    python "$CASSIOPEE/Dist/bin/$ELSAPROD/notifyValid.py" "$@"
else
    python "$CASSIOPEE/Dist/bin/$ELSAPROD/notifyValid.pyc" "$@"
fi
