#! /bin/sh
echo 'Installing CPlot tests and doc'
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    PRODUCTION=0
    # Destination docs
    DEST="$CASSIOPEE/Dist/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/CPlot"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 1 ])
then
    PRODUCTION=0
    # Destination docs
    DEST="$1/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/CPlot"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 2 ])
then
    PRODUCTION=1
    # Destination docs
    DEST="$CASSIOPEE/WWW/cassiopee-web"
    # Destination tests unitaires
    DEST2="$DEST/Examples/CPlot"
    # Destination des release notes
    DEST3="$CASSIOPEE/WWW/Main/Download"
else
    echo 'install: install in $CASSIOPEE/Dist/doc'
    echo 'install <dir>: install in directory <dir/doc>.'
    exit
fi

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi
    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Apps/Modules/CPlot/test Examples/CPlot
fi
cd ..

# Build html
sphinx-build -b html ./source ./build
if ([ $PRODUCTION -eq 1 ])
then
# Build pdf
    sphinx-build -b latex ./source ./build
    cd build
    pdflatex CPlot
    pdflatex tkCassiopee
    pdflatex tkPlotXY
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    taghtml build/CPlot.html
    sed -i 's/CPlot.CPlot/CPlot/g' build/CPlot.html
    cp build/CPlot.html $DEST

    taghtml build/tkCassiopee.html
    sed -i 's/CPlot.pdf/tkCassiopee.pdf/g' build/tkCassiopee.html
    cp build/tkCassiopee.html $DEST

    taghtml build/tkPlotXY.html
    sed -i 's/CPlot.pdf/tkPlotXY.pdf/g' build/tkPlotXY.html
    cp build/tkPlotXY.html $DEST

    cp build/CPlot.pdf $DEST
    cp build/tkCassiopee.pdf $DEST
    cp build/tkPlotXY.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../CPlot/CPlot.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='CPlot-'$version1'.txt'
    cp CPlot.txt $DEST3/$v
fi
