#! /bin/sh
#
# ./install -> installation dans Cassiopee/Dist/bin/ELSAPROD
# ./install <dir> -> installation dans <dir>
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit 1
    fi
    if [ "$ELSAPROD" = "" ]; then
        export ELSAPROD=x86_r8
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or-'
    echo 'install <dir>: install in directory <dir>.'
    exit 1
fi

# if specific python exe name
if [ "$PYTHONEXE" != "" ]; then
    alias python=$PYTHONEXE
fi

# set production mode (0: scons+setup, 1: scons+pip, 2: scons+pip+wheel)
if [ "$PRODMODE" = "" ]; then
    PRODMODE=0
fi

# Compilation et installation
if [ $PRODMODE -eq 0 ]; then # setup
    python setup.py install --prefix="$INSTALLPATH"
    [ $? != 0 ] && exit 1;
elif [ $PRODMODE -eq 1 ]; then # pip
    python -m pip install --ignore-installed --upgrade --prefix="$INSTALLPATH" .
    [ $? != 0 ] && exit 1;
elif [ $PRODMODE -eq 2 ]; then # pip+wheel
    TMPDIR=$INSTALLPATH python -m pip install --ignore-installed --upgrade --prefix="$INSTALLPATH" --no-clean .
    [ $? != 0 ] && exit 1;
fi

# Check installation
python test/t1.py
