LIBNAME = Metric
SOURCEF90 = 
SOURCEF77 = \
CompTetraCellCenterF.for\
CompStructCellCenterF.for\
CompVolOfStructCellF.for \
CompVolOfTetraCellF.for \
CompMeanLengthOfCellF.for\
CompMinLengthOfCellF.for\
CompIntSurfOfCellF.for\
CompIntSurfF.for \
CompStructSurfF.for\
CompCenterInterfaceF.for \
CompStructMetricF.for\
CompUnstrSurfF.for\
CompUnstrCenterIntF.for\
CompUnstrMetricF.for\
CompNormStructSurfF.for\
CompNormUnstrSurfF.for
include ../Make.inc
