#! /bin/sh
#
# ./install -> installation dans Cassiopee/Dist/bin/ELSAPROD
# ./install <dir> -> installation dans <dir>
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    if [ "$ELSAPROD" = "" ]; then
        export ELSAPROD=x86_r8
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or-'
    echo 'install <dir>: install in directory <dir>.'
    exit
fi

# Compilation et installation
python3 setup.py install --prefix="$INSTALLPATH"

# Check installation
python3 test/t1.py
