#! /bin/sh
#
# Installation de Compressor
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    if [ "$ELSAPROD" = "" ]; then
        export ELSAPROD=x86_r8
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or- '
    echo 'install <dir>: install in directory <dir>.'
    exit
fi

# Compilation et installation
which scons &>/dev/null
if [ $? -eq 0 ]; then
    if [ "$OMP_NUM_THREADS" != "" ]; then
        export SCONSOPT="-j $OMP_NUM_THREADS"
    else
        export SCONSOPT=""
    fi
    scons install prefix="$INSTALLPATH" "$SCONSOPT"
    [ $? != 0 ] && exit;
    #touch Compressor/compressor.cpp
    rm -f build/lib.*/Compressor/compressor.*
    python setupScons.py install --prefix="$INSTALLPATH"
else
    python setup.py install --prefix="$INSTALLPATH"
fi

# Test l'installation
python test/t1.py
