#! /bin/sh
#
# Installation de CPlot
#
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit 1
    fi
    if [ "$ELSAPROD" = "" ]; then
        export ELSAPROD=x86_r8
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo ' -or- '
    echo 'install <dir>: install in directory <dir>.'
    exit 1
fi

# if specific python exe name
if [ "$PYTHONEXE" != "" ]; then
    alias python=$PYTHONEXE
fi

# set production mode (0: scons+setup, 1: scons+pip, 2: scons+pip+wheel)
if [ "$PRODMODE" = "" ]; then
    PRODMODE=0
fi

# Compilation et installation
if [ $PRODMODE -ge 0 ]; then
    sconsf=`which scons`
    if [ "$OMP_NUM_THREADS" != "" ]; then
        export SCONSOPT="-j $OMP_NUM_THREADS"
    else
        export SCONSOPT=""
    fi
    if [ -x "$sconsf" ]; then
        if head -c 100 "$sconsf" | grep -q python; then
            python $sconsf install prefix="$INSTALLPATH" "$SCONSOPT"
        else
            $sconsf install prefix="$INSTALLPATH" "$SCONSOPT"
        fi
    else
        python $sconsf install prefix="$INSTALLPATH" "$SCONSOPT"
    fi
    [ $? != 0 ] && exit 1;
    #touch CPlot/cplot.cpp
    rm -f build/lib.*/CPlot/cplot.*
    rm -f build/lib.*/CPlot/cplot-*.*
    rm -f build/lib.*/CPlot/cplotOSMesa.*
    rm -f build/lib.*/CPlot/cplotOSMesa-*.*
    if [ $PRODMODE -eq 0 ]; then # setup
        python setup.py install --prefix="$INSTALLPATH"
        [ $? != 0 ] && exit 1;
    elif [ $PRODMODE -eq 1 ]; then # pip
        python -m pip install --ignore-installed --upgrade --prefix="$INSTALLPATH" .
        [ $? != 0 ] && exit 1;
    elif [ $PRODMODE -eq 2 ]; then # pip+wheel
        TMPDIR=$INSTALLPATH python -m pip install --ignore-installed --upgrade --prefix="$INSTALLPATH" --no-clean .
        [ $? != 0 ] && exit 1;
    elif [ $PRODMODE -eq 3 ]; then # pip no isolation
        python -m pip install --no-build-isolation --ignore-installed --upgrade --prefix="$INSTALLPATH" .
        [ $? != 0 ] && exit 1;
    fi
else
    python setupLegacy.py install --prefix="$INSTALLPATH"
    [ $? != 0 ] && exit 1;
fi

cp test/cplot "$INSTALLPATH"
cp test/cplot.py "$INSTALLPATH"
# Copie les applications
cp apps/*.py "$INSTALLPATH"
cp apps/cassiopee "$INSTALLPATH"
cp apps/appCassiopee "$INSTALLPATH"
cp apps/CCC "$INSTALLPATH"
cp apps/cassiopee.bat "$INSTALLPATH"
cp apps/cassiopeeRunWin32.bat "$INSTALLPATH"
cp apps/cassiopeeRunWin64.bat "$INSTALLPATH"
cp apps/validCassiopee "$INSTALLPATH"
cp apps/validCassiopee.bat "$INSTALLPATH"
cp apps/kcgnsview "$INSTALLPATH"
python installThemes.py

# Test l'installation
python test/t1.py
