#! /bin/sh
# Dans Dist : 
# - enleve les pyc (a appeler pour remettre le Dist ok apres binex)
if ([ $# -eq 0 ])
then
    if [ "$CASSIOPEE" = "" ]; then
        echo "You must specify a CASSIOPEE variable in your environment."
        echo "This variable specifies the installation path of *Cassiopee*."
        exit
    fi
    if [ "$ELSAPROD" = "" ]; then
        echo "You must specify a ELSAPROD in your environment."
        echo "This variable identifies the processor type."
        exit
    fi
    INSTALLPATH="$CASSIOPEE/Dist/bin/$ELSAPROD"

elif ([ $# -eq 1 ])
then
    if [ "$ELSAPROD" = "" ]; then
        echo "You must specify a ELSAPROD in your environment."
        echo "This variable identifies the processor type."
        exit
    fi
    INSTALLPATH="$1"
else
    echo 'install: install in $CASSIOPEE/Dist/bin/$ELSAPROD'
    echo 'install <dir>: install in directory <dir>.'
    exit
fi

cd $INSTALLPATH

# compile les .py dans la racine (supprime car tout est open source)
#    ret=`ls '*.pyc'`
#    for i in $ret; do
#        rm -f $i
#    done



if test -e  "lib/site-packages"
then
    cd lib/site-packages
else
    cd lib/python3.8/site-packages
fi

pwd

# Compile les .py, enleve les .py dans les modules
. $CASSIOPEE/Apps/Modules/MODULES
FULLMODULES='Apps'
for mod in $FULLMODULES
do
   echo 'removing pyc in '$mod
   if test -e "$mod"
   then
       cd $mod
       ret=`/usr/bin/find . -name '*.pyc'`
       for i in $ret; do
           rm -f $i
       done
       cd ..
    fi
done

. $CASSIOPEE/Apps/PModules/MODULES
FULLMODULES=''
for mod in $FULLMODULES
do
   echo 'removing pyc in '$mod
   if [ "$mod" == "FFX" ]
   then
       mod="Ffx"
   fi
   if [ "$mod" == "FFD" ]
   then
       mod="Ffd"
   fi
   if test -e "$mod"
   then
       cd $mod
       ret=`/usr/bin/find . -name '*.pyc'`
       for i in $ret; do
           rm -f $i
       done
       cd ..
    fi
done
