#! /bin/sh
echo 'Installing Post tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

if ([ $# -eq 0 ])
then
    PRODUCTION=0
    # Destination docs
    DEST="./doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Post"
    # Destination des release notes
    DEST3="$DEST"
elif ([ $# -eq 2 ])
then
    PRODUCTION=1
    # Destination docs
    DEST="$CASSIOPEE/docs/doc"
    # Destination tests unitaires
    DEST2="$DEST/Examples/Post"
    # Destination des release notes
    DEST3="$CASSIOPEE/docs/Download"
else
    echo 'install: install locally'
    echo 'install <dir>: install in docs/doc.'
    exit
fi

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi

    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Cassiopee/Post/test Examples/Post
fi
cd ..

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build
if ([ $PRODUCTION -eq 1 ])
then
# Build pdf
    sphinx-build -b latex ./source ./build
    cd build
    pdflatex Post >& /dev/null
    pdflatex Rotor >& /dev/null
    pdflatex ExtraVariables2 >& /dev/null
    pdflatex Post_IBM >& /dev/null
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    sed -i 's/Post.Post/Post/g' build/Post.html
    cp build/Post.html $DEST
    cp build/Post.pdf $DEST

    sed -i 's/Post.Rotor.Post.Rotor/Post.Rotor/g' build/Rotor.html
    sed -i 's/Post\.pdf/Rotor\.pdf/g' build/Rotor.html
    cp build/Rotor.html $DEST
    cp build/Rotor.pdf $DEST

    sed -i 's/Post.ExtraVariables2.Post.ExtraVariables2/Post.ExtraVariables2/g' build/ExtraVariables2.html
    sed -i 's/Post\.pdf/ExtraVariables2\.pdf/g' build/ExtraVariables2.html
    cp build/ExtraVariables2.html $DEST
    cp build/ExtraVariables2.pdf $DEST

    sed -i 's/Post.Post_IBM.Post.Post_IBM/Post.Post_IBM/g' build/Post_IBM.html
    sed -i 's/Post\.pdf/Post_IBM\.pdf/g' build/Post_IBM.html
    cp build/Post_IBM.html $DEST
    cp build/Post_IBM.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../Post/Post.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='Post-'$version1'.txt'
    cp Post.txt $DEST3/$v
fi
