#! /bin/sh
echo 'Installing CPlot tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi
	
PRODUCTION=1
# Destination docs
DEST="$CASSIOPEE/docs/doc"
# Destination tests unitaires
DEST2="$DEST/Examples/CPlot"
# Destination des release notes
DEST3="$CASSIOPEE/docs/Download"

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi
    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Cassiopee/CPlot/test Examples/CPlot
fi
cd ..

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build
[ $? != 0 ] && exit 1;
if ([ $PRODUCTION -eq 1 ])
then
    # Build pdf
    sphinx-build -b latex ./source ./build
    [ $? != 0 ] && exit 1;
    cd build
    pdflatex CPlot
    [ $? != 0 ] && exit 1;
    pdflatex tkCassiopee
    [ $? != 0 ] && exit 1;
    pdflatex tkPlotXY
    [ $? != 0 ] && exit 1;
    pdflatex Decorator
    [ $? != 0 ] && exit 1;
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    sed -i 's/CPlot.CPlot/.CPlot/g' build/CPlot.html
    cp build/CPlot.html $DEST
    
    sed -i 's/CPlot.pdf/tkCassiopee.pdf/g' build/tkCassiopee.html
    cp build/tkCassiopee.html $DEST

    sed -i 's/CPlot.pdf/tkPlotXY.pdf/g' build/tkPlotXY.html
    cp build/tkPlotXY.html $DEST

    sed -i 's/CPlot\.Decorator\.CPlot\.Decorator/CPlot\.Decorator/g' build/Decorator.html
    sed -i 's/CPlot.pdf/Decorator.pdf/g' build/Decorator.html
    cp build/Decorator.html $DEST
    
    cp build/_images/*png $DEST/_images
    
    cp build/CPlot.pdf $DEST
    cp build/tkCassiopee.pdf $DEST
    cp build/tkPlotXY.pdf $DEST
    cp build/Decorator.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../CPlot/CPlot.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='CPlot-'$version1'.txt'
    cp CPlot.txt $DEST3/$v
fi
