#!/bin/sh
echo 'Installing OCC tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

PRODUCTION=1
# Destination docs
DEST="$CASSIOPEE/docs/doc"
# Destination tests unitaires
DEST2="$DEST/Examples/OCC"
# Destination des release notes
DEST3="$CASSIOPEE/docs/Download"

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi

    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Cassiopee/OCC/test Examples/OCC
fi
cd ..

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build
[ $? != 0 ] && exit 1;
if ([ $PRODUCTION -eq 1 ])
then
# Build pdf
    sphinx-build -b latex ./source ./build
    [ $? != 0 ] && exit 1;
    cd build
    pdflatex OCC
    [ $? != 0 ] && exit 1;
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    sed -i 's/OCC.OCC/OCC/g' build/OCC.html
    cp build/OCC.html $DEST
    cp build/OCC.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../OCC/OCC.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='OCC-'$version1'.txt'
    cp OCC.txt $DEST3/$v
fi
