#! /bin/sh
echo 'Installing Generator tests and doc'
if [ "$CASSIOPEE" = "" ]; then
    echo "You must specify a CASSIOPEE variable in your environment."
    echo "This variable specifies the installation path of *Cassiopee*."
    exit
fi

PRODUCTION=1
# Destination docs
DEST="$CASSIOPEE/docs/doc"
# Destination tests unitaires
DEST2="$DEST/Examples/Generator"
# Destination des release notes
DEST3="$CASSIOPEE/docs/Download"

# Copy examples to global dir (production mod)
if ([ $PRODUCTION -eq 1 ])
then
    if test ! -e $DEST
    then 
        mkdir $DEST
    fi
    if test ! -e "$DEST/Examples"
    then 
        mkdir "$DEST/Examples"
    fi
    if test ! -e $DEST2
    then 
        mkdir $DEST2
    fi
    if test ! -e $DEST3
    then 
        mkdir $DEST3
    fi

    cp ../test/*.py $DEST2
fi

# Create Links for Examples (local)
if test ! -e build
then
    mkdir build
fi
cd build
if test ! -e Examples
then
    mkdir Examples
    ln -s $CASSIOPEE/Cassiopee/Generator/test Examples/Generator
fi
cd ..

# Build html
touch source/*.rst
sphinx-build -b html ./source ./build
if ([ $PRODUCTION -eq 1 ])
then
# Build pdf
    sphinx-build -b latex ./source ./build
    cd build
    pdflatex Generator >& /dev/null
    pdflatex Generator_IBM >& /dev/null
    cd ..
fi

# Copie dans le DEST
if ([ $PRODUCTION -eq 1 ])
then
    sed -i 's/Generator.Generator/Generator/g' build/Generator.html
    cp build/Generator.html $DEST
    cp build/Generator.pdf $DEST

    sed -i 's/Generator.Generator_IBM.Generator.Generator_IBM/Generator.Generator_IBM/g' build/Generator_IBM.html
    sed -i 's/Generator\.pdf/Generator_IBM\.pdf/g' build/Generator_IBM.html
    cp build/Generator_IBM.html $DEST
    cp build/Generator_IBM.pdf $DEST
fi

# Copie des release Notes
if ([ $PRODUCTION -eq 1 ])
then
    version=`grep -e __version__ ../Generator/Generator.py`
    version1=${version:15:4}
    version1=${version1/"'"/""}
    v='Generator-'$version1'.txt'
    cp Generator.txt $DEST3/$v
fi
