name: docker

on:
  workflow_dispatch:  # allows manual trigger
  push:
    tags:
      - 'v*'
    branches:
      - 'docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.12, 3.10.5, 3.12.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Print GitHub context
        run: |
          echo "Building for Python ${{ matrix.python-version }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: cassiopee486/cassiopee:${{ github.ref_name }}-py${{ matrix.python-version }}
